// Code generated by ent, DO NOT EDIT.

package upstreamconnection

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the upstreamconnection type in the database.
	Label = "upstream_connection"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldBaseURL holds the string denoting the base_url field in the database.
	FieldBaseURL = "base_url"
	// FieldAuthMode holds the string denoting the auth_mode field in the database.
	FieldAuthMode = "auth_mode"
	// FieldCredentialsEncrypted holds the string denoting the credentials_encrypted field in the database.
	FieldCredentialsEncrypted = "credentials_encrypted"
	// FieldAccessTokenEncrypted holds the string denoting the access_token_encrypted field in the database.
	FieldAccessTokenEncrypted = "access_token_encrypted"
	// FieldRefreshTokenEncrypted holds the string denoting the refresh_token_encrypted field in the database.
	FieldRefreshTokenEncrypted = "refresh_token_encrypted"
	// FieldTokenExpiresAt holds the string denoting the token_expires_at field in the database.
	FieldTokenExpiresAt = "token_expires_at"
	// FieldEnabled holds the string denoting the enabled field in the database.
	FieldEnabled = "enabled"
	// FieldIntervalMinutes holds the string denoting the interval_minutes field in the database.
	FieldIntervalMinutes = "interval_minutes"
	// FieldLastSyncAt holds the string denoting the last_sync_at field in the database.
	FieldLastSyncAt = "last_sync_at"
	// FieldLastStatus holds the string denoting the last_status field in the database.
	FieldLastStatus = "last_status"
	// FieldLastError holds the string denoting the last_error field in the database.
	FieldLastError = "last_error"
	// EdgeSyncRuns holds the string denoting the sync_runs edge name in mutations.
	EdgeSyncRuns = "sync_runs"
	// Table holds the table name of the upstreamconnection in the database.
	Table = "upstream_connections"
	// SyncRunsTable is the table that holds the sync_runs relation/edge.
	SyncRunsTable = "upstream_sync_runs"
	// SyncRunsInverseTable is the table name for the UpstreamSyncRun entity.
	// It exists in this package in order to avoid circular dependency with the "upstreamsyncrun" package.
	SyncRunsInverseTable = "upstream_sync_runs"
	// SyncRunsColumn is the table column denoting the sync_runs relation/edge.
	SyncRunsColumn = "connection_id"
)

// Columns holds all SQL columns for upstreamconnection fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldBaseURL,
	FieldAuthMode,
	FieldCredentialsEncrypted,
	FieldAccessTokenEncrypted,
	FieldRefreshTokenEncrypted,
	FieldTokenExpiresAt,
	FieldEnabled,
	FieldIntervalMinutes,
	FieldLastSyncAt,
	FieldLastStatus,
	FieldLastError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// BaseURLValidator is a validator for the "base_url" field. It is called by the builders before save.
	BaseURLValidator func(string) error
	// DefaultEnabled holds the default value on creation for the "enabled" field.
	DefaultEnabled bool
	// DefaultIntervalMinutes holds the default value on creation for the "interval_minutes" field.
	DefaultIntervalMinutes int
	// LastStatusValidator is a validator for the "last_status" field. It is called by the builders before save.
	LastStatusValidator func(string) error
)

// AuthMode defines the type for the "auth_mode" enum field.
type AuthMode string

// AuthMode values.
const (
	AuthModePassword AuthMode = "password"
	AuthModeToken    AuthMode = "token"
)

func (am AuthMode) String() string {
	return string(am)
}

// AuthModeValidator is a validator for the "auth_mode" field enum values. It is called by the builders before save.
func AuthModeValidator(am AuthMode) error {
	switch am {
	case AuthModePassword, AuthModeToken:
		return nil
	default:
		return fmt.Errorf("upstreamconnection: invalid enum value for auth_mode field: %q", am)
	}
}

// OrderOption defines the ordering options for the UpstreamConnection queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByBaseURL orders the results by the base_url field.
func ByBaseURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBaseURL, opts...).ToFunc()
}

// ByAuthMode orders the results by the auth_mode field.
func ByAuthMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthMode, opts...).ToFunc()
}

// ByCredentialsEncrypted orders the results by the credentials_encrypted field.
func ByCredentialsEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCredentialsEncrypted, opts...).ToFunc()
}

// ByAccessTokenEncrypted orders the results by the access_token_encrypted field.
func ByAccessTokenEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccessTokenEncrypted, opts...).ToFunc()
}

// ByRefreshTokenEncrypted orders the results by the refresh_token_encrypted field.
func ByRefreshTokenEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRefreshTokenEncrypted, opts...).ToFunc()
}

// ByTokenExpiresAt orders the results by the token_expires_at field.
func ByTokenExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokenExpiresAt, opts...).ToFunc()
}

// ByEnabled orders the results by the enabled field.
func ByEnabled(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEnabled, opts...).ToFunc()
}

// ByIntervalMinutes orders the results by the interval_minutes field.
func ByIntervalMinutes(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIntervalMinutes, opts...).ToFunc()
}

// ByLastSyncAt orders the results by the last_sync_at field.
func ByLastSyncAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastSyncAt, opts...).ToFunc()
}

// ByLastStatus orders the results by the last_status field.
func ByLastStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastStatus, opts...).ToFunc()
}

// ByLastError orders the results by the last_error field.
func ByLastError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastError, opts...).ToFunc()
}

// BySyncRunsCount orders the results by sync_runs count.
func BySyncRunsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSyncRunsStep(), opts...)
	}
}

// BySyncRuns orders the results by sync_runs terms.
func BySyncRuns(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSyncRunsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newSyncRunsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SyncRunsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, SyncRunsTable, SyncRunsColumn),
	)
}
