// Code generated by ent, DO NOT EDIT.

package upstreamconnection

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldName, v))
}

// BaseURL applies equality check predicate on the "base_url" field. It's identical to BaseURLEQ.
func BaseURL(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldBaseURL, v))
}

// CredentialsEncrypted applies equality check predicate on the "credentials_encrypted" field. It's identical to CredentialsEncryptedEQ.
func CredentialsEncrypted(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldCredentialsEncrypted, v))
}

// AccessTokenEncrypted applies equality check predicate on the "access_token_encrypted" field. It's identical to AccessTokenEncryptedEQ.
func AccessTokenEncrypted(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldAccessTokenEncrypted, v))
}

// RefreshTokenEncrypted applies equality check predicate on the "refresh_token_encrypted" field. It's identical to RefreshTokenEncryptedEQ.
func RefreshTokenEncrypted(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldRefreshTokenEncrypted, v))
}

// TokenExpiresAt applies equality check predicate on the "token_expires_at" field. It's identical to TokenExpiresAtEQ.
func TokenExpiresAt(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldTokenExpiresAt, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldEnabled, v))
}

// IntervalMinutes applies equality check predicate on the "interval_minutes" field. It's identical to IntervalMinutesEQ.
func IntervalMinutes(v int) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldIntervalMinutes, v))
}

// LastSyncAt applies equality check predicate on the "last_sync_at" field. It's identical to LastSyncAtEQ.
func LastSyncAt(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldLastSyncAt, v))
}

// LastStatus applies equality check predicate on the "last_status" field. It's identical to LastStatusEQ.
func LastStatus(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldLastStatus, v))
}

// LastError applies equality check predicate on the "last_error" field. It's identical to LastErrorEQ.
func LastError(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldLastError, v))
}

// LastBalance applies equality check predicate on the "last_balance" field. It's identical to LastBalanceEQ.
func LastBalance(v float64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldLastBalance, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContainsFold(FieldName, v))
}

// BaseURLEQ applies the EQ predicate on the "base_url" field.
func BaseURLEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldBaseURL, v))
}

// BaseURLNEQ applies the NEQ predicate on the "base_url" field.
func BaseURLNEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldBaseURL, v))
}

// BaseURLIn applies the In predicate on the "base_url" field.
func BaseURLIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldBaseURL, vs...))
}

// BaseURLNotIn applies the NotIn predicate on the "base_url" field.
func BaseURLNotIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldBaseURL, vs...))
}

// BaseURLGT applies the GT predicate on the "base_url" field.
func BaseURLGT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldBaseURL, v))
}

// BaseURLGTE applies the GTE predicate on the "base_url" field.
func BaseURLGTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldBaseURL, v))
}

// BaseURLLT applies the LT predicate on the "base_url" field.
func BaseURLLT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldBaseURL, v))
}

// BaseURLLTE applies the LTE predicate on the "base_url" field.
func BaseURLLTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldBaseURL, v))
}

// BaseURLContains applies the Contains predicate on the "base_url" field.
func BaseURLContains(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContains(FieldBaseURL, v))
}

// BaseURLHasPrefix applies the HasPrefix predicate on the "base_url" field.
func BaseURLHasPrefix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasPrefix(FieldBaseURL, v))
}

// BaseURLHasSuffix applies the HasSuffix predicate on the "base_url" field.
func BaseURLHasSuffix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasSuffix(FieldBaseURL, v))
}

// BaseURLEqualFold applies the EqualFold predicate on the "base_url" field.
func BaseURLEqualFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEqualFold(FieldBaseURL, v))
}

// BaseURLContainsFold applies the ContainsFold predicate on the "base_url" field.
func BaseURLContainsFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContainsFold(FieldBaseURL, v))
}

// AuthModeEQ applies the EQ predicate on the "auth_mode" field.
func AuthModeEQ(v AuthMode) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldAuthMode, v))
}

// AuthModeNEQ applies the NEQ predicate on the "auth_mode" field.
func AuthModeNEQ(v AuthMode) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldAuthMode, v))
}

// AuthModeIn applies the In predicate on the "auth_mode" field.
func AuthModeIn(vs ...AuthMode) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldAuthMode, vs...))
}

// AuthModeNotIn applies the NotIn predicate on the "auth_mode" field.
func AuthModeNotIn(vs ...AuthMode) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldAuthMode, vs...))
}

// CredentialsEncryptedEQ applies the EQ predicate on the "credentials_encrypted" field.
func CredentialsEncryptedEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldCredentialsEncrypted, v))
}

// CredentialsEncryptedNEQ applies the NEQ predicate on the "credentials_encrypted" field.
func CredentialsEncryptedNEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldCredentialsEncrypted, v))
}

// CredentialsEncryptedIn applies the In predicate on the "credentials_encrypted" field.
func CredentialsEncryptedIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldCredentialsEncrypted, vs...))
}

// CredentialsEncryptedNotIn applies the NotIn predicate on the "credentials_encrypted" field.
func CredentialsEncryptedNotIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldCredentialsEncrypted, vs...))
}

// CredentialsEncryptedGT applies the GT predicate on the "credentials_encrypted" field.
func CredentialsEncryptedGT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldCredentialsEncrypted, v))
}

// CredentialsEncryptedGTE applies the GTE predicate on the "credentials_encrypted" field.
func CredentialsEncryptedGTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldCredentialsEncrypted, v))
}

// CredentialsEncryptedLT applies the LT predicate on the "credentials_encrypted" field.
func CredentialsEncryptedLT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldCredentialsEncrypted, v))
}

// CredentialsEncryptedLTE applies the LTE predicate on the "credentials_encrypted" field.
func CredentialsEncryptedLTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldCredentialsEncrypted, v))
}

// CredentialsEncryptedContains applies the Contains predicate on the "credentials_encrypted" field.
func CredentialsEncryptedContains(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContains(FieldCredentialsEncrypted, v))
}

// CredentialsEncryptedHasPrefix applies the HasPrefix predicate on the "credentials_encrypted" field.
func CredentialsEncryptedHasPrefix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasPrefix(FieldCredentialsEncrypted, v))
}

// CredentialsEncryptedHasSuffix applies the HasSuffix predicate on the "credentials_encrypted" field.
func CredentialsEncryptedHasSuffix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasSuffix(FieldCredentialsEncrypted, v))
}

// CredentialsEncryptedIsNil applies the IsNil predicate on the "credentials_encrypted" field.
func CredentialsEncryptedIsNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIsNull(FieldCredentialsEncrypted))
}

// CredentialsEncryptedNotNil applies the NotNil predicate on the "credentials_encrypted" field.
func CredentialsEncryptedNotNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotNull(FieldCredentialsEncrypted))
}

// CredentialsEncryptedEqualFold applies the EqualFold predicate on the "credentials_encrypted" field.
func CredentialsEncryptedEqualFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEqualFold(FieldCredentialsEncrypted, v))
}

// CredentialsEncryptedContainsFold applies the ContainsFold predicate on the "credentials_encrypted" field.
func CredentialsEncryptedContainsFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContainsFold(FieldCredentialsEncrypted, v))
}

// AccessTokenEncryptedEQ applies the EQ predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedNEQ applies the NEQ predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedNEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedIn applies the In predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldAccessTokenEncrypted, vs...))
}

// AccessTokenEncryptedNotIn applies the NotIn predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedNotIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldAccessTokenEncrypted, vs...))
}

// AccessTokenEncryptedGT applies the GT predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedGT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedGTE applies the GTE predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedGTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedLT applies the LT predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedLT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedLTE applies the LTE predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedLTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedContains applies the Contains predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedContains(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContains(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedHasPrefix applies the HasPrefix predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedHasPrefix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasPrefix(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedHasSuffix applies the HasSuffix predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedHasSuffix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasSuffix(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedIsNil applies the IsNil predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedIsNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIsNull(FieldAccessTokenEncrypted))
}

// AccessTokenEncryptedNotNil applies the NotNil predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedNotNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotNull(FieldAccessTokenEncrypted))
}

// AccessTokenEncryptedEqualFold applies the EqualFold predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedEqualFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEqualFold(FieldAccessTokenEncrypted, v))
}

// AccessTokenEncryptedContainsFold applies the ContainsFold predicate on the "access_token_encrypted" field.
func AccessTokenEncryptedContainsFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContainsFold(FieldAccessTokenEncrypted, v))
}

// RefreshTokenEncryptedEQ applies the EQ predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedNEQ applies the NEQ predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedNEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedIn applies the In predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldRefreshTokenEncrypted, vs...))
}

// RefreshTokenEncryptedNotIn applies the NotIn predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedNotIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldRefreshTokenEncrypted, vs...))
}

// RefreshTokenEncryptedGT applies the GT predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedGT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedGTE applies the GTE predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedGTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedLT applies the LT predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedLT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedLTE applies the LTE predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedLTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedContains applies the Contains predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedContains(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContains(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedHasPrefix applies the HasPrefix predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedHasPrefix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasPrefix(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedHasSuffix applies the HasSuffix predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedHasSuffix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasSuffix(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedIsNil applies the IsNil predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedIsNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIsNull(FieldRefreshTokenEncrypted))
}

// RefreshTokenEncryptedNotNil applies the NotNil predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedNotNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotNull(FieldRefreshTokenEncrypted))
}

// RefreshTokenEncryptedEqualFold applies the EqualFold predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedEqualFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEqualFold(FieldRefreshTokenEncrypted, v))
}

// RefreshTokenEncryptedContainsFold applies the ContainsFold predicate on the "refresh_token_encrypted" field.
func RefreshTokenEncryptedContainsFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContainsFold(FieldRefreshTokenEncrypted, v))
}

// TokenExpiresAtEQ applies the EQ predicate on the "token_expires_at" field.
func TokenExpiresAtEQ(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldTokenExpiresAt, v))
}

// TokenExpiresAtNEQ applies the NEQ predicate on the "token_expires_at" field.
func TokenExpiresAtNEQ(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldTokenExpiresAt, v))
}

// TokenExpiresAtIn applies the In predicate on the "token_expires_at" field.
func TokenExpiresAtIn(vs ...time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldTokenExpiresAt, vs...))
}

// TokenExpiresAtNotIn applies the NotIn predicate on the "token_expires_at" field.
func TokenExpiresAtNotIn(vs ...time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldTokenExpiresAt, vs...))
}

// TokenExpiresAtGT applies the GT predicate on the "token_expires_at" field.
func TokenExpiresAtGT(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldTokenExpiresAt, v))
}

// TokenExpiresAtGTE applies the GTE predicate on the "token_expires_at" field.
func TokenExpiresAtGTE(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldTokenExpiresAt, v))
}

// TokenExpiresAtLT applies the LT predicate on the "token_expires_at" field.
func TokenExpiresAtLT(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldTokenExpiresAt, v))
}

// TokenExpiresAtLTE applies the LTE predicate on the "token_expires_at" field.
func TokenExpiresAtLTE(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldTokenExpiresAt, v))
}

// TokenExpiresAtIsNil applies the IsNil predicate on the "token_expires_at" field.
func TokenExpiresAtIsNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIsNull(FieldTokenExpiresAt))
}

// TokenExpiresAtNotNil applies the NotNil predicate on the "token_expires_at" field.
func TokenExpiresAtNotNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotNull(FieldTokenExpiresAt))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldEnabled, v))
}

// IntervalMinutesEQ applies the EQ predicate on the "interval_minutes" field.
func IntervalMinutesEQ(v int) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldIntervalMinutes, v))
}

// IntervalMinutesNEQ applies the NEQ predicate on the "interval_minutes" field.
func IntervalMinutesNEQ(v int) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldIntervalMinutes, v))
}

// IntervalMinutesIn applies the In predicate on the "interval_minutes" field.
func IntervalMinutesIn(vs ...int) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldIntervalMinutes, vs...))
}

// IntervalMinutesNotIn applies the NotIn predicate on the "interval_minutes" field.
func IntervalMinutesNotIn(vs ...int) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldIntervalMinutes, vs...))
}

// IntervalMinutesGT applies the GT predicate on the "interval_minutes" field.
func IntervalMinutesGT(v int) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldIntervalMinutes, v))
}

// IntervalMinutesGTE applies the GTE predicate on the "interval_minutes" field.
func IntervalMinutesGTE(v int) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldIntervalMinutes, v))
}

// IntervalMinutesLT applies the LT predicate on the "interval_minutes" field.
func IntervalMinutesLT(v int) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldIntervalMinutes, v))
}

// IntervalMinutesLTE applies the LTE predicate on the "interval_minutes" field.
func IntervalMinutesLTE(v int) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldIntervalMinutes, v))
}

// LastSyncAtEQ applies the EQ predicate on the "last_sync_at" field.
func LastSyncAtEQ(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldLastSyncAt, v))
}

// LastSyncAtNEQ applies the NEQ predicate on the "last_sync_at" field.
func LastSyncAtNEQ(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldLastSyncAt, v))
}

// LastSyncAtIn applies the In predicate on the "last_sync_at" field.
func LastSyncAtIn(vs ...time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldLastSyncAt, vs...))
}

// LastSyncAtNotIn applies the NotIn predicate on the "last_sync_at" field.
func LastSyncAtNotIn(vs ...time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldLastSyncAt, vs...))
}

// LastSyncAtGT applies the GT predicate on the "last_sync_at" field.
func LastSyncAtGT(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldLastSyncAt, v))
}

// LastSyncAtGTE applies the GTE predicate on the "last_sync_at" field.
func LastSyncAtGTE(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldLastSyncAt, v))
}

// LastSyncAtLT applies the LT predicate on the "last_sync_at" field.
func LastSyncAtLT(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldLastSyncAt, v))
}

// LastSyncAtLTE applies the LTE predicate on the "last_sync_at" field.
func LastSyncAtLTE(v time.Time) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldLastSyncAt, v))
}

// LastSyncAtIsNil applies the IsNil predicate on the "last_sync_at" field.
func LastSyncAtIsNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIsNull(FieldLastSyncAt))
}

// LastSyncAtNotNil applies the NotNil predicate on the "last_sync_at" field.
func LastSyncAtNotNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotNull(FieldLastSyncAt))
}

// LastStatusEQ applies the EQ predicate on the "last_status" field.
func LastStatusEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldLastStatus, v))
}

// LastStatusNEQ applies the NEQ predicate on the "last_status" field.
func LastStatusNEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldLastStatus, v))
}

// LastStatusIn applies the In predicate on the "last_status" field.
func LastStatusIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldLastStatus, vs...))
}

// LastStatusNotIn applies the NotIn predicate on the "last_status" field.
func LastStatusNotIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldLastStatus, vs...))
}

// LastStatusGT applies the GT predicate on the "last_status" field.
func LastStatusGT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldLastStatus, v))
}

// LastStatusGTE applies the GTE predicate on the "last_status" field.
func LastStatusGTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldLastStatus, v))
}

// LastStatusLT applies the LT predicate on the "last_status" field.
func LastStatusLT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldLastStatus, v))
}

// LastStatusLTE applies the LTE predicate on the "last_status" field.
func LastStatusLTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldLastStatus, v))
}

// LastStatusContains applies the Contains predicate on the "last_status" field.
func LastStatusContains(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContains(FieldLastStatus, v))
}

// LastStatusHasPrefix applies the HasPrefix predicate on the "last_status" field.
func LastStatusHasPrefix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasPrefix(FieldLastStatus, v))
}

// LastStatusHasSuffix applies the HasSuffix predicate on the "last_status" field.
func LastStatusHasSuffix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasSuffix(FieldLastStatus, v))
}

// LastStatusIsNil applies the IsNil predicate on the "last_status" field.
func LastStatusIsNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIsNull(FieldLastStatus))
}

// LastStatusNotNil applies the NotNil predicate on the "last_status" field.
func LastStatusNotNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotNull(FieldLastStatus))
}

// LastStatusEqualFold applies the EqualFold predicate on the "last_status" field.
func LastStatusEqualFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEqualFold(FieldLastStatus, v))
}

// LastStatusContainsFold applies the ContainsFold predicate on the "last_status" field.
func LastStatusContainsFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContainsFold(FieldLastStatus, v))
}

// LastErrorEQ applies the EQ predicate on the "last_error" field.
func LastErrorEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldLastError, v))
}

// LastErrorNEQ applies the NEQ predicate on the "last_error" field.
func LastErrorNEQ(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldLastError, v))
}

// LastErrorIn applies the In predicate on the "last_error" field.
func LastErrorIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldLastError, vs...))
}

// LastErrorNotIn applies the NotIn predicate on the "last_error" field.
func LastErrorNotIn(vs ...string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldLastError, vs...))
}

// LastErrorGT applies the GT predicate on the "last_error" field.
func LastErrorGT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldLastError, v))
}

// LastErrorGTE applies the GTE predicate on the "last_error" field.
func LastErrorGTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldLastError, v))
}

// LastErrorLT applies the LT predicate on the "last_error" field.
func LastErrorLT(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldLastError, v))
}

// LastErrorLTE applies the LTE predicate on the "last_error" field.
func LastErrorLTE(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldLastError, v))
}

// LastErrorContains applies the Contains predicate on the "last_error" field.
func LastErrorContains(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContains(FieldLastError, v))
}

// LastErrorHasPrefix applies the HasPrefix predicate on the "last_error" field.
func LastErrorHasPrefix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasPrefix(FieldLastError, v))
}

// LastErrorHasSuffix applies the HasSuffix predicate on the "last_error" field.
func LastErrorHasSuffix(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldHasSuffix(FieldLastError, v))
}

// LastErrorIsNil applies the IsNil predicate on the "last_error" field.
func LastErrorIsNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIsNull(FieldLastError))
}

// LastErrorNotNil applies the NotNil predicate on the "last_error" field.
func LastErrorNotNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotNull(FieldLastError))
}

// LastErrorEqualFold applies the EqualFold predicate on the "last_error" field.
func LastErrorEqualFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEqualFold(FieldLastError, v))
}

// LastErrorContainsFold applies the ContainsFold predicate on the "last_error" field.
func LastErrorContainsFold(v string) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldContainsFold(FieldLastError, v))
}

// LastBalanceEQ applies the EQ predicate on the "last_balance" field.
func LastBalanceEQ(v float64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldEQ(FieldLastBalance, v))
}

// LastBalanceNEQ applies the NEQ predicate on the "last_balance" field.
func LastBalanceNEQ(v float64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNEQ(FieldLastBalance, v))
}

// LastBalanceIn applies the In predicate on the "last_balance" field.
func LastBalanceIn(vs ...float64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIn(FieldLastBalance, vs...))
}

// LastBalanceNotIn applies the NotIn predicate on the "last_balance" field.
func LastBalanceNotIn(vs ...float64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotIn(FieldLastBalance, vs...))
}

// LastBalanceGT applies the GT predicate on the "last_balance" field.
func LastBalanceGT(v float64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGT(FieldLastBalance, v))
}

// LastBalanceGTE applies the GTE predicate on the "last_balance" field.
func LastBalanceGTE(v float64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldGTE(FieldLastBalance, v))
}

// LastBalanceLT applies the LT predicate on the "last_balance" field.
func LastBalanceLT(v float64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLT(FieldLastBalance, v))
}

// LastBalanceLTE applies the LTE predicate on the "last_balance" field.
func LastBalanceLTE(v float64) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldLTE(FieldLastBalance, v))
}

// LastBalanceIsNil applies the IsNil predicate on the "last_balance" field.
func LastBalanceIsNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldIsNull(FieldLastBalance))
}

// LastBalanceNotNil applies the NotNil predicate on the "last_balance" field.
func LastBalanceNotNil() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.FieldNotNull(FieldLastBalance))
}

// HasSyncRuns applies the HasEdge predicate on the "sync_runs" edge.
func HasSyncRuns() predicate.UpstreamConnection {
	return predicate.UpstreamConnection(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, SyncRunsTable, SyncRunsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSyncRunsWith applies the HasEdge predicate on the "sync_runs" edge with a given conditions (other predicates).
func HasSyncRunsWith(preds ...predicate.UpstreamSyncRun) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(func(s *sql.Selector) {
		step := newSyncRunsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamConnection) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamConnection) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamConnection) predicate.UpstreamConnection {
	return predicate.UpstreamConnection(sql.NotPredicates(p))
}
