// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconnection"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsyncrun"
)

// UpstreamConnectionUpdate is the builder for updating UpstreamConnection entities.
type UpstreamConnectionUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamConnectionMutation
}

// Where appends a list predicates to the UpstreamConnectionUpdate builder.
func (_u *UpstreamConnectionUpdate) Where(ps ...predicate.UpstreamConnection) *UpstreamConnectionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamConnectionUpdate) SetUpdatedAt(v time.Time) *UpstreamConnectionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamConnectionUpdate) SetName(v string) *UpstreamConnectionUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableName(v *string) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *UpstreamConnectionUpdate) SetBaseURL(v string) *UpstreamConnectionUpdate {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableBaseURL(v *string) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetAuthMode sets the "auth_mode" field.
func (_u *UpstreamConnectionUpdate) SetAuthMode(v upstreamconnection.AuthMode) *UpstreamConnectionUpdate {
	_u.mutation.SetAuthMode(v)
	return _u
}

// SetNillableAuthMode sets the "auth_mode" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableAuthMode(v *upstreamconnection.AuthMode) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetAuthMode(*v)
	}
	return _u
}

// SetCredentialsEncrypted sets the "credentials_encrypted" field.
func (_u *UpstreamConnectionUpdate) SetCredentialsEncrypted(v string) *UpstreamConnectionUpdate {
	_u.mutation.SetCredentialsEncrypted(v)
	return _u
}

// SetNillableCredentialsEncrypted sets the "credentials_encrypted" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableCredentialsEncrypted(v *string) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetCredentialsEncrypted(*v)
	}
	return _u
}

// ClearCredentialsEncrypted clears the value of the "credentials_encrypted" field.
func (_u *UpstreamConnectionUpdate) ClearCredentialsEncrypted() *UpstreamConnectionUpdate {
	_u.mutation.ClearCredentialsEncrypted()
	return _u
}

// SetAccessTokenEncrypted sets the "access_token_encrypted" field.
func (_u *UpstreamConnectionUpdate) SetAccessTokenEncrypted(v string) *UpstreamConnectionUpdate {
	_u.mutation.SetAccessTokenEncrypted(v)
	return _u
}

// SetNillableAccessTokenEncrypted sets the "access_token_encrypted" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableAccessTokenEncrypted(v *string) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetAccessTokenEncrypted(*v)
	}
	return _u
}

// ClearAccessTokenEncrypted clears the value of the "access_token_encrypted" field.
func (_u *UpstreamConnectionUpdate) ClearAccessTokenEncrypted() *UpstreamConnectionUpdate {
	_u.mutation.ClearAccessTokenEncrypted()
	return _u
}

// SetRefreshTokenEncrypted sets the "refresh_token_encrypted" field.
func (_u *UpstreamConnectionUpdate) SetRefreshTokenEncrypted(v string) *UpstreamConnectionUpdate {
	_u.mutation.SetRefreshTokenEncrypted(v)
	return _u
}

// SetNillableRefreshTokenEncrypted sets the "refresh_token_encrypted" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableRefreshTokenEncrypted(v *string) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetRefreshTokenEncrypted(*v)
	}
	return _u
}

// ClearRefreshTokenEncrypted clears the value of the "refresh_token_encrypted" field.
func (_u *UpstreamConnectionUpdate) ClearRefreshTokenEncrypted() *UpstreamConnectionUpdate {
	_u.mutation.ClearRefreshTokenEncrypted()
	return _u
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (_u *UpstreamConnectionUpdate) SetTokenExpiresAt(v time.Time) *UpstreamConnectionUpdate {
	_u.mutation.SetTokenExpiresAt(v)
	return _u
}

// SetNillableTokenExpiresAt sets the "token_expires_at" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableTokenExpiresAt(v *time.Time) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetTokenExpiresAt(*v)
	}
	return _u
}

// ClearTokenExpiresAt clears the value of the "token_expires_at" field.
func (_u *UpstreamConnectionUpdate) ClearTokenExpiresAt() *UpstreamConnectionUpdate {
	_u.mutation.ClearTokenExpiresAt()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UpstreamConnectionUpdate) SetEnabled(v bool) *UpstreamConnectionUpdate {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableEnabled(v *bool) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetIntervalMinutes sets the "interval_minutes" field.
func (_u *UpstreamConnectionUpdate) SetIntervalMinutes(v int) *UpstreamConnectionUpdate {
	_u.mutation.ResetIntervalMinutes()
	_u.mutation.SetIntervalMinutes(v)
	return _u
}

// SetNillableIntervalMinutes sets the "interval_minutes" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableIntervalMinutes(v *int) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetIntervalMinutes(*v)
	}
	return _u
}

// AddIntervalMinutes adds value to the "interval_minutes" field.
func (_u *UpstreamConnectionUpdate) AddIntervalMinutes(v int) *UpstreamConnectionUpdate {
	_u.mutation.AddIntervalMinutes(v)
	return _u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_u *UpstreamConnectionUpdate) SetLastSyncAt(v time.Time) *UpstreamConnectionUpdate {
	_u.mutation.SetLastSyncAt(v)
	return _u
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableLastSyncAt(v *time.Time) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetLastSyncAt(*v)
	}
	return _u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (_u *UpstreamConnectionUpdate) ClearLastSyncAt() *UpstreamConnectionUpdate {
	_u.mutation.ClearLastSyncAt()
	return _u
}

// SetLastStatus sets the "last_status" field.
func (_u *UpstreamConnectionUpdate) SetLastStatus(v string) *UpstreamConnectionUpdate {
	_u.mutation.SetLastStatus(v)
	return _u
}

// SetNillableLastStatus sets the "last_status" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableLastStatus(v *string) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetLastStatus(*v)
	}
	return _u
}

// ClearLastStatus clears the value of the "last_status" field.
func (_u *UpstreamConnectionUpdate) ClearLastStatus() *UpstreamConnectionUpdate {
	_u.mutation.ClearLastStatus()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *UpstreamConnectionUpdate) SetLastError(v string) *UpstreamConnectionUpdate {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableLastError(v *string) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *UpstreamConnectionUpdate) ClearLastError() *UpstreamConnectionUpdate {
	_u.mutation.ClearLastError()
	return _u
}

// SetLastBalance sets the "last_balance" field.
func (_u *UpstreamConnectionUpdate) SetLastBalance(v float64) *UpstreamConnectionUpdate {
	_u.mutation.ResetLastBalance()
	_u.mutation.SetLastBalance(v)
	return _u
}

// SetNillableLastBalance sets the "last_balance" field if the given value is not nil.
func (_u *UpstreamConnectionUpdate) SetNillableLastBalance(v *float64) *UpstreamConnectionUpdate {
	if v != nil {
		_u.SetLastBalance(*v)
	}
	return _u
}

// AddLastBalance adds value to the "last_balance" field.
func (_u *UpstreamConnectionUpdate) AddLastBalance(v float64) *UpstreamConnectionUpdate {
	_u.mutation.AddLastBalance(v)
	return _u
}

// ClearLastBalance clears the value of the "last_balance" field.
func (_u *UpstreamConnectionUpdate) ClearLastBalance() *UpstreamConnectionUpdate {
	_u.mutation.ClearLastBalance()
	return _u
}

// AddSyncRunIDs adds the "sync_runs" edge to the UpstreamSyncRun entity by IDs.
func (_u *UpstreamConnectionUpdate) AddSyncRunIDs(ids ...int64) *UpstreamConnectionUpdate {
	_u.mutation.AddSyncRunIDs(ids...)
	return _u
}

// AddSyncRuns adds the "sync_runs" edges to the UpstreamSyncRun entity.
func (_u *UpstreamConnectionUpdate) AddSyncRuns(v ...*UpstreamSyncRun) *UpstreamConnectionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSyncRunIDs(ids...)
}

// Mutation returns the UpstreamConnectionMutation object of the builder.
func (_u *UpstreamConnectionUpdate) Mutation() *UpstreamConnectionMutation {
	return _u.mutation
}

// ClearSyncRuns clears all "sync_runs" edges to the UpstreamSyncRun entity.
func (_u *UpstreamConnectionUpdate) ClearSyncRuns() *UpstreamConnectionUpdate {
	_u.mutation.ClearSyncRuns()
	return _u
}

// RemoveSyncRunIDs removes the "sync_runs" edge to UpstreamSyncRun entities by IDs.
func (_u *UpstreamConnectionUpdate) RemoveSyncRunIDs(ids ...int64) *UpstreamConnectionUpdate {
	_u.mutation.RemoveSyncRunIDs(ids...)
	return _u
}

// RemoveSyncRuns removes "sync_runs" edges to UpstreamSyncRun entities.
func (_u *UpstreamConnectionUpdate) RemoveSyncRuns(v ...*UpstreamSyncRun) *UpstreamConnectionUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSyncRunIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamConnectionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamConnectionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamConnectionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamConnectionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamConnectionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamconnection.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamConnectionUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreamconnection.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := upstreamconnection.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMode(); ok {
		if err := upstreamconnection.AuthModeValidator(v); err != nil {
			return &ValidationError{Name: "auth_mode", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.auth_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastStatus(); ok {
		if err := upstreamconnection.LastStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_status", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.last_status": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamConnectionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamconnection.Table, upstreamconnection.Columns, sqlgraph.NewFieldSpec(upstreamconnection.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamconnection.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreamconnection.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(upstreamconnection.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthMode(); ok {
		_spec.SetField(upstreamconnection.FieldAuthMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CredentialsEncrypted(); ok {
		_spec.SetField(upstreamconnection.FieldCredentialsEncrypted, field.TypeString, value)
	}
	if _u.mutation.CredentialsEncryptedCleared() {
		_spec.ClearField(upstreamconnection.FieldCredentialsEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.AccessTokenEncrypted(); ok {
		_spec.SetField(upstreamconnection.FieldAccessTokenEncrypted, field.TypeString, value)
	}
	if _u.mutation.AccessTokenEncryptedCleared() {
		_spec.ClearField(upstreamconnection.FieldAccessTokenEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshTokenEncrypted(); ok {
		_spec.SetField(upstreamconnection.FieldRefreshTokenEncrypted, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenEncryptedCleared() {
		_spec.ClearField(upstreamconnection.FieldRefreshTokenEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.TokenExpiresAt(); ok {
		_spec.SetField(upstreamconnection.FieldTokenExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.TokenExpiresAtCleared() {
		_spec.ClearField(upstreamconnection.FieldTokenExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(upstreamconnection.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IntervalMinutes(); ok {
		_spec.SetField(upstreamconnection.FieldIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalMinutes(); ok {
		_spec.AddField(upstreamconnection.FieldIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastSyncAt(); ok {
		_spec.SetField(upstreamconnection.FieldLastSyncAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncAtCleared() {
		_spec.ClearField(upstreamconnection.FieldLastSyncAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastStatus(); ok {
		_spec.SetField(upstreamconnection.FieldLastStatus, field.TypeString, value)
	}
	if _u.mutation.LastStatusCleared() {
		_spec.ClearField(upstreamconnection.FieldLastStatus, field.TypeString)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(upstreamconnection.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(upstreamconnection.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.LastBalance(); ok {
		_spec.SetField(upstreamconnection.FieldLastBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLastBalance(); ok {
		_spec.AddField(upstreamconnection.FieldLastBalance, field.TypeFloat64, value)
	}
	if _u.mutation.LastBalanceCleared() {
		_spec.ClearField(upstreamconnection.FieldLastBalance, field.TypeFloat64)
	}
	if _u.mutation.SyncRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamconnection.SyncRunsTable,
			Columns: []string{upstreamconnection.SyncRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsyncrun.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSyncRunsIDs(); len(nodes) > 0 && !_u.mutation.SyncRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamconnection.SyncRunsTable,
			Columns: []string{upstreamconnection.SyncRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsyncrun.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SyncRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamconnection.SyncRunsTable,
			Columns: []string{upstreamconnection.SyncRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsyncrun.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamconnection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamConnectionUpdateOne is the builder for updating a single UpstreamConnection entity.
type UpstreamConnectionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamConnectionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *UpstreamConnectionUpdateOne) SetUpdatedAt(v time.Time) *UpstreamConnectionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *UpstreamConnectionUpdateOne) SetName(v string) *UpstreamConnectionUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableName(v *string) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetBaseURL sets the "base_url" field.
func (_u *UpstreamConnectionUpdateOne) SetBaseURL(v string) *UpstreamConnectionUpdateOne {
	_u.mutation.SetBaseURL(v)
	return _u
}

// SetNillableBaseURL sets the "base_url" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableBaseURL(v *string) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetBaseURL(*v)
	}
	return _u
}

// SetAuthMode sets the "auth_mode" field.
func (_u *UpstreamConnectionUpdateOne) SetAuthMode(v upstreamconnection.AuthMode) *UpstreamConnectionUpdateOne {
	_u.mutation.SetAuthMode(v)
	return _u
}

// SetNillableAuthMode sets the "auth_mode" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableAuthMode(v *upstreamconnection.AuthMode) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetAuthMode(*v)
	}
	return _u
}

// SetCredentialsEncrypted sets the "credentials_encrypted" field.
func (_u *UpstreamConnectionUpdateOne) SetCredentialsEncrypted(v string) *UpstreamConnectionUpdateOne {
	_u.mutation.SetCredentialsEncrypted(v)
	return _u
}

// SetNillableCredentialsEncrypted sets the "credentials_encrypted" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableCredentialsEncrypted(v *string) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetCredentialsEncrypted(*v)
	}
	return _u
}

// ClearCredentialsEncrypted clears the value of the "credentials_encrypted" field.
func (_u *UpstreamConnectionUpdateOne) ClearCredentialsEncrypted() *UpstreamConnectionUpdateOne {
	_u.mutation.ClearCredentialsEncrypted()
	return _u
}

// SetAccessTokenEncrypted sets the "access_token_encrypted" field.
func (_u *UpstreamConnectionUpdateOne) SetAccessTokenEncrypted(v string) *UpstreamConnectionUpdateOne {
	_u.mutation.SetAccessTokenEncrypted(v)
	return _u
}

// SetNillableAccessTokenEncrypted sets the "access_token_encrypted" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableAccessTokenEncrypted(v *string) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetAccessTokenEncrypted(*v)
	}
	return _u
}

// ClearAccessTokenEncrypted clears the value of the "access_token_encrypted" field.
func (_u *UpstreamConnectionUpdateOne) ClearAccessTokenEncrypted() *UpstreamConnectionUpdateOne {
	_u.mutation.ClearAccessTokenEncrypted()
	return _u
}

// SetRefreshTokenEncrypted sets the "refresh_token_encrypted" field.
func (_u *UpstreamConnectionUpdateOne) SetRefreshTokenEncrypted(v string) *UpstreamConnectionUpdateOne {
	_u.mutation.SetRefreshTokenEncrypted(v)
	return _u
}

// SetNillableRefreshTokenEncrypted sets the "refresh_token_encrypted" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableRefreshTokenEncrypted(v *string) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetRefreshTokenEncrypted(*v)
	}
	return _u
}

// ClearRefreshTokenEncrypted clears the value of the "refresh_token_encrypted" field.
func (_u *UpstreamConnectionUpdateOne) ClearRefreshTokenEncrypted() *UpstreamConnectionUpdateOne {
	_u.mutation.ClearRefreshTokenEncrypted()
	return _u
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (_u *UpstreamConnectionUpdateOne) SetTokenExpiresAt(v time.Time) *UpstreamConnectionUpdateOne {
	_u.mutation.SetTokenExpiresAt(v)
	return _u
}

// SetNillableTokenExpiresAt sets the "token_expires_at" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableTokenExpiresAt(v *time.Time) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetTokenExpiresAt(*v)
	}
	return _u
}

// ClearTokenExpiresAt clears the value of the "token_expires_at" field.
func (_u *UpstreamConnectionUpdateOne) ClearTokenExpiresAt() *UpstreamConnectionUpdateOne {
	_u.mutation.ClearTokenExpiresAt()
	return _u
}

// SetEnabled sets the "enabled" field.
func (_u *UpstreamConnectionUpdateOne) SetEnabled(v bool) *UpstreamConnectionUpdateOne {
	_u.mutation.SetEnabled(v)
	return _u
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableEnabled(v *bool) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetEnabled(*v)
	}
	return _u
}

// SetIntervalMinutes sets the "interval_minutes" field.
func (_u *UpstreamConnectionUpdateOne) SetIntervalMinutes(v int) *UpstreamConnectionUpdateOne {
	_u.mutation.ResetIntervalMinutes()
	_u.mutation.SetIntervalMinutes(v)
	return _u
}

// SetNillableIntervalMinutes sets the "interval_minutes" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableIntervalMinutes(v *int) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetIntervalMinutes(*v)
	}
	return _u
}

// AddIntervalMinutes adds value to the "interval_minutes" field.
func (_u *UpstreamConnectionUpdateOne) AddIntervalMinutes(v int) *UpstreamConnectionUpdateOne {
	_u.mutation.AddIntervalMinutes(v)
	return _u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_u *UpstreamConnectionUpdateOne) SetLastSyncAt(v time.Time) *UpstreamConnectionUpdateOne {
	_u.mutation.SetLastSyncAt(v)
	return _u
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableLastSyncAt(v *time.Time) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetLastSyncAt(*v)
	}
	return _u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (_u *UpstreamConnectionUpdateOne) ClearLastSyncAt() *UpstreamConnectionUpdateOne {
	_u.mutation.ClearLastSyncAt()
	return _u
}

// SetLastStatus sets the "last_status" field.
func (_u *UpstreamConnectionUpdateOne) SetLastStatus(v string) *UpstreamConnectionUpdateOne {
	_u.mutation.SetLastStatus(v)
	return _u
}

// SetNillableLastStatus sets the "last_status" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableLastStatus(v *string) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetLastStatus(*v)
	}
	return _u
}

// ClearLastStatus clears the value of the "last_status" field.
func (_u *UpstreamConnectionUpdateOne) ClearLastStatus() *UpstreamConnectionUpdateOne {
	_u.mutation.ClearLastStatus()
	return _u
}

// SetLastError sets the "last_error" field.
func (_u *UpstreamConnectionUpdateOne) SetLastError(v string) *UpstreamConnectionUpdateOne {
	_u.mutation.SetLastError(v)
	return _u
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableLastError(v *string) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetLastError(*v)
	}
	return _u
}

// ClearLastError clears the value of the "last_error" field.
func (_u *UpstreamConnectionUpdateOne) ClearLastError() *UpstreamConnectionUpdateOne {
	_u.mutation.ClearLastError()
	return _u
}

// SetLastBalance sets the "last_balance" field.
func (_u *UpstreamConnectionUpdateOne) SetLastBalance(v float64) *UpstreamConnectionUpdateOne {
	_u.mutation.ResetLastBalance()
	_u.mutation.SetLastBalance(v)
	return _u
}

// SetNillableLastBalance sets the "last_balance" field if the given value is not nil.
func (_u *UpstreamConnectionUpdateOne) SetNillableLastBalance(v *float64) *UpstreamConnectionUpdateOne {
	if v != nil {
		_u.SetLastBalance(*v)
	}
	return _u
}

// AddLastBalance adds value to the "last_balance" field.
func (_u *UpstreamConnectionUpdateOne) AddLastBalance(v float64) *UpstreamConnectionUpdateOne {
	_u.mutation.AddLastBalance(v)
	return _u
}

// ClearLastBalance clears the value of the "last_balance" field.
func (_u *UpstreamConnectionUpdateOne) ClearLastBalance() *UpstreamConnectionUpdateOne {
	_u.mutation.ClearLastBalance()
	return _u
}

// AddSyncRunIDs adds the "sync_runs" edge to the UpstreamSyncRun entity by IDs.
func (_u *UpstreamConnectionUpdateOne) AddSyncRunIDs(ids ...int64) *UpstreamConnectionUpdateOne {
	_u.mutation.AddSyncRunIDs(ids...)
	return _u
}

// AddSyncRuns adds the "sync_runs" edges to the UpstreamSyncRun entity.
func (_u *UpstreamConnectionUpdateOne) AddSyncRuns(v ...*UpstreamSyncRun) *UpstreamConnectionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddSyncRunIDs(ids...)
}

// Mutation returns the UpstreamConnectionMutation object of the builder.
func (_u *UpstreamConnectionUpdateOne) Mutation() *UpstreamConnectionMutation {
	return _u.mutation
}

// ClearSyncRuns clears all "sync_runs" edges to the UpstreamSyncRun entity.
func (_u *UpstreamConnectionUpdateOne) ClearSyncRuns() *UpstreamConnectionUpdateOne {
	_u.mutation.ClearSyncRuns()
	return _u
}

// RemoveSyncRunIDs removes the "sync_runs" edge to UpstreamSyncRun entities by IDs.
func (_u *UpstreamConnectionUpdateOne) RemoveSyncRunIDs(ids ...int64) *UpstreamConnectionUpdateOne {
	_u.mutation.RemoveSyncRunIDs(ids...)
	return _u
}

// RemoveSyncRuns removes "sync_runs" edges to UpstreamSyncRun entities.
func (_u *UpstreamConnectionUpdateOne) RemoveSyncRuns(v ...*UpstreamSyncRun) *UpstreamConnectionUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveSyncRunIDs(ids...)
}

// Where appends a list predicates to the UpstreamConnectionUpdate builder.
func (_u *UpstreamConnectionUpdateOne) Where(ps ...predicate.UpstreamConnection) *UpstreamConnectionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamConnectionUpdateOne) Select(field string, fields ...string) *UpstreamConnectionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamConnection entity.
func (_u *UpstreamConnectionUpdateOne) Save(ctx context.Context) (*UpstreamConnection, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamConnectionUpdateOne) SaveX(ctx context.Context) *UpstreamConnection {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamConnectionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamConnectionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *UpstreamConnectionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := upstreamconnection.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamConnectionUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := upstreamconnection.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BaseURL(); ok {
		if err := upstreamconnection.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.base_url": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AuthMode(); ok {
		if err := upstreamconnection.AuthModeValidator(v); err != nil {
			return &ValidationError{Name: "auth_mode", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.auth_mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LastStatus(); ok {
		if err := upstreamconnection.LastStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_status", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.last_status": %w`, err)}
		}
	}
	return nil
}

func (_u *UpstreamConnectionUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamConnection, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamconnection.Table, upstreamconnection.Columns, sqlgraph.NewFieldSpec(upstreamconnection.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamConnection.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamconnection.FieldID)
		for _, f := range fields {
			if !upstreamconnection.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamconnection.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamconnection.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(upstreamconnection.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.BaseURL(); ok {
		_spec.SetField(upstreamconnection.FieldBaseURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.AuthMode(); ok {
		_spec.SetField(upstreamconnection.FieldAuthMode, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.CredentialsEncrypted(); ok {
		_spec.SetField(upstreamconnection.FieldCredentialsEncrypted, field.TypeString, value)
	}
	if _u.mutation.CredentialsEncryptedCleared() {
		_spec.ClearField(upstreamconnection.FieldCredentialsEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.AccessTokenEncrypted(); ok {
		_spec.SetField(upstreamconnection.FieldAccessTokenEncrypted, field.TypeString, value)
	}
	if _u.mutation.AccessTokenEncryptedCleared() {
		_spec.ClearField(upstreamconnection.FieldAccessTokenEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.RefreshTokenEncrypted(); ok {
		_spec.SetField(upstreamconnection.FieldRefreshTokenEncrypted, field.TypeString, value)
	}
	if _u.mutation.RefreshTokenEncryptedCleared() {
		_spec.ClearField(upstreamconnection.FieldRefreshTokenEncrypted, field.TypeString)
	}
	if value, ok := _u.mutation.TokenExpiresAt(); ok {
		_spec.SetField(upstreamconnection.FieldTokenExpiresAt, field.TypeTime, value)
	}
	if _u.mutation.TokenExpiresAtCleared() {
		_spec.ClearField(upstreamconnection.FieldTokenExpiresAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Enabled(); ok {
		_spec.SetField(upstreamconnection.FieldEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.IntervalMinutes(); ok {
		_spec.SetField(upstreamconnection.FieldIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedIntervalMinutes(); ok {
		_spec.AddField(upstreamconnection.FieldIntervalMinutes, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastSyncAt(); ok {
		_spec.SetField(upstreamconnection.FieldLastSyncAt, field.TypeTime, value)
	}
	if _u.mutation.LastSyncAtCleared() {
		_spec.ClearField(upstreamconnection.FieldLastSyncAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastStatus(); ok {
		_spec.SetField(upstreamconnection.FieldLastStatus, field.TypeString, value)
	}
	if _u.mutation.LastStatusCleared() {
		_spec.ClearField(upstreamconnection.FieldLastStatus, field.TypeString)
	}
	if value, ok := _u.mutation.LastError(); ok {
		_spec.SetField(upstreamconnection.FieldLastError, field.TypeString, value)
	}
	if _u.mutation.LastErrorCleared() {
		_spec.ClearField(upstreamconnection.FieldLastError, field.TypeString)
	}
	if value, ok := _u.mutation.LastBalance(); ok {
		_spec.SetField(upstreamconnection.FieldLastBalance, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedLastBalance(); ok {
		_spec.AddField(upstreamconnection.FieldLastBalance, field.TypeFloat64, value)
	}
	if _u.mutation.LastBalanceCleared() {
		_spec.ClearField(upstreamconnection.FieldLastBalance, field.TypeFloat64)
	}
	if _u.mutation.SyncRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamconnection.SyncRunsTable,
			Columns: []string{upstreamconnection.SyncRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsyncrun.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedSyncRunsIDs(); len(nodes) > 0 && !_u.mutation.SyncRunsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamconnection.SyncRunsTable,
			Columns: []string{upstreamconnection.SyncRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsyncrun.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.SyncRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamconnection.SyncRunsTable,
			Columns: []string{upstreamconnection.SyncRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsyncrun.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UpstreamConnection{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamconnection.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
