// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconnection"
)

// UpstreamConnection is the model entity for the UpstreamConnection schema.
type UpstreamConnection struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// 归一化后的上游 base_url（小写 scheme/host、去尾斜杠、去默认端口），全局唯一，作为连接作用域隔离键
	BaseURL string `json:"base_url,omitempty"`
	// AuthMode holds the value of the "auth_mode" field.
	AuthMode upstreamconnection.AuthMode `json:"auth_mode,omitempty"`
	// password 模式账密 / token 模式手贴 access token 的密文
	CredentialsEncrypted string `json:"-"`
	// AccessTokenEncrypted holds the value of the "access_token_encrypted" field.
	AccessTokenEncrypted string `json:"-"`
	// RefreshTokenEncrypted holds the value of the "refresh_token_encrypted" field.
	RefreshTokenEncrypted string `json:"-"`
	// access token 到期时间，到期前提前刷新
	TokenExpiresAt *time.Time `json:"token_expires_at,omitempty"`
	// 定时同步开关，默认关闭
	Enabled bool `json:"enabled,omitempty"`
	// 同步间隔（分钟），合法边界 5–1440（service 层校验）
	IntervalMinutes int `json:"interval_minutes,omitempty"`
	// LastSyncAt holds the value of the "last_sync_at" field.
	LastSyncAt *time.Time `json:"last_sync_at,omitempty"`
	// 最近一次同步结果：success|partial|failed
	LastStatus string `json:"last_status,omitempty"`
	// 最近一次错误摘要（脱敏，不含 token/密码）
	LastError string `json:"last_error,omitempty"`
	// 最近一次同步读取到的上游账号余额（USD），nil 表示未获取过
	LastBalance *float64 `json:"last_balance,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UpstreamConnectionQuery when eager-loading is set.
	Edges        UpstreamConnectionEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UpstreamConnectionEdges holds the relations/edges for other nodes in the graph.
type UpstreamConnectionEdges struct {
	// SyncRuns holds the value of the sync_runs edge.
	SyncRuns []*UpstreamSyncRun `json:"sync_runs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// SyncRunsOrErr returns the SyncRuns value or an error if the edge
// was not loaded in eager-loading.
func (e UpstreamConnectionEdges) SyncRunsOrErr() ([]*UpstreamSyncRun, error) {
	if e.loadedTypes[0] {
		return e.SyncRuns, nil
	}
	return nil, &NotLoadedError{edge: "sync_runs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamConnection) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamconnection.FieldEnabled:
			values[i] = new(sql.NullBool)
		case upstreamconnection.FieldLastBalance:
			values[i] = new(sql.NullFloat64)
		case upstreamconnection.FieldID, upstreamconnection.FieldIntervalMinutes:
			values[i] = new(sql.NullInt64)
		case upstreamconnection.FieldName, upstreamconnection.FieldBaseURL, upstreamconnection.FieldAuthMode, upstreamconnection.FieldCredentialsEncrypted, upstreamconnection.FieldAccessTokenEncrypted, upstreamconnection.FieldRefreshTokenEncrypted, upstreamconnection.FieldLastStatus, upstreamconnection.FieldLastError:
			values[i] = new(sql.NullString)
		case upstreamconnection.FieldCreatedAt, upstreamconnection.FieldUpdatedAt, upstreamconnection.FieldTokenExpiresAt, upstreamconnection.FieldLastSyncAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamConnection fields.
func (_m *UpstreamConnection) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamconnection.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamconnection.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case upstreamconnection.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case upstreamconnection.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case upstreamconnection.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case upstreamconnection.FieldAuthMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_mode", values[i])
			} else if value.Valid {
				_m.AuthMode = upstreamconnection.AuthMode(value.String)
			}
		case upstreamconnection.FieldCredentialsEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field credentials_encrypted", values[i])
			} else if value.Valid {
				_m.CredentialsEncrypted = value.String
			}
		case upstreamconnection.FieldAccessTokenEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field access_token_encrypted", values[i])
			} else if value.Valid {
				_m.AccessTokenEncrypted = value.String
			}
		case upstreamconnection.FieldRefreshTokenEncrypted:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refresh_token_encrypted", values[i])
			} else if value.Valid {
				_m.RefreshTokenEncrypted = value.String
			}
		case upstreamconnection.FieldTokenExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field token_expires_at", values[i])
			} else if value.Valid {
				_m.TokenExpiresAt = new(time.Time)
				*_m.TokenExpiresAt = value.Time
			}
		case upstreamconnection.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case upstreamconnection.FieldIntervalMinutes:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field interval_minutes", values[i])
			} else if value.Valid {
				_m.IntervalMinutes = int(value.Int64)
			}
		case upstreamconnection.FieldLastSyncAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_sync_at", values[i])
			} else if value.Valid {
				_m.LastSyncAt = new(time.Time)
				*_m.LastSyncAt = value.Time
			}
		case upstreamconnection.FieldLastStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_status", values[i])
			} else if value.Valid {
				_m.LastStatus = value.String
			}
		case upstreamconnection.FieldLastError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_error", values[i])
			} else if value.Valid {
				_m.LastError = value.String
			}
		case upstreamconnection.FieldLastBalance:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field last_balance", values[i])
			} else if value.Valid {
				_m.LastBalance = new(float64)
				*_m.LastBalance = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamConnection.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamConnection) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySyncRuns queries the "sync_runs" edge of the UpstreamConnection entity.
func (_m *UpstreamConnection) QuerySyncRuns() *UpstreamSyncRunQuery {
	return NewUpstreamConnectionClient(_m.config).QuerySyncRuns(_m)
}

// Update returns a builder for updating this UpstreamConnection.
// Note that you need to call UpstreamConnection.Unwrap() before calling this method if this UpstreamConnection
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamConnection) Update() *UpstreamConnectionUpdateOne {
	return NewUpstreamConnectionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamConnection entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamConnection) Unwrap() *UpstreamConnection {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamConnection is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamConnection) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamConnection(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	builder.WriteString("auth_mode=")
	builder.WriteString(fmt.Sprintf("%v", _m.AuthMode))
	builder.WriteString(", ")
	builder.WriteString("credentials_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("access_token_encrypted=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("refresh_token_encrypted=<sensitive>")
	builder.WriteString(", ")
	if v := _m.TokenExpiresAt; v != nil {
		builder.WriteString("token_expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("interval_minutes=")
	builder.WriteString(fmt.Sprintf("%v", _m.IntervalMinutes))
	builder.WriteString(", ")
	if v := _m.LastSyncAt; v != nil {
		builder.WriteString("last_sync_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_status=")
	builder.WriteString(_m.LastStatus)
	builder.WriteString(", ")
	builder.WriteString("last_error=")
	builder.WriteString(_m.LastError)
	builder.WriteString(", ")
	if v := _m.LastBalance; v != nil {
		builder.WriteString("last_balance=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamConnections is a parsable slice of UpstreamConnection.
type UpstreamConnections []*UpstreamConnection
