// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconnection"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsyncrun"
)

// UpstreamConnectionCreate is the builder for creating a UpstreamConnection entity.
type UpstreamConnectionCreate struct {
	config
	mutation *UpstreamConnectionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *UpstreamConnectionCreate) SetCreatedAt(v time.Time) *UpstreamConnectionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableCreatedAt(v *time.Time) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UpstreamConnectionCreate) SetUpdatedAt(v time.Time) *UpstreamConnectionCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableUpdatedAt(v *time.Time) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *UpstreamConnectionCreate) SetName(v string) *UpstreamConnectionCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetBaseURL sets the "base_url" field.
func (_c *UpstreamConnectionCreate) SetBaseURL(v string) *UpstreamConnectionCreate {
	_c.mutation.SetBaseURL(v)
	return _c
}

// SetAuthMode sets the "auth_mode" field.
func (_c *UpstreamConnectionCreate) SetAuthMode(v upstreamconnection.AuthMode) *UpstreamConnectionCreate {
	_c.mutation.SetAuthMode(v)
	return _c
}

// SetCredentialsEncrypted sets the "credentials_encrypted" field.
func (_c *UpstreamConnectionCreate) SetCredentialsEncrypted(v string) *UpstreamConnectionCreate {
	_c.mutation.SetCredentialsEncrypted(v)
	return _c
}

// SetNillableCredentialsEncrypted sets the "credentials_encrypted" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableCredentialsEncrypted(v *string) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetCredentialsEncrypted(*v)
	}
	return _c
}

// SetAccessTokenEncrypted sets the "access_token_encrypted" field.
func (_c *UpstreamConnectionCreate) SetAccessTokenEncrypted(v string) *UpstreamConnectionCreate {
	_c.mutation.SetAccessTokenEncrypted(v)
	return _c
}

// SetNillableAccessTokenEncrypted sets the "access_token_encrypted" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableAccessTokenEncrypted(v *string) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetAccessTokenEncrypted(*v)
	}
	return _c
}

// SetRefreshTokenEncrypted sets the "refresh_token_encrypted" field.
func (_c *UpstreamConnectionCreate) SetRefreshTokenEncrypted(v string) *UpstreamConnectionCreate {
	_c.mutation.SetRefreshTokenEncrypted(v)
	return _c
}

// SetNillableRefreshTokenEncrypted sets the "refresh_token_encrypted" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableRefreshTokenEncrypted(v *string) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetRefreshTokenEncrypted(*v)
	}
	return _c
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (_c *UpstreamConnectionCreate) SetTokenExpiresAt(v time.Time) *UpstreamConnectionCreate {
	_c.mutation.SetTokenExpiresAt(v)
	return _c
}

// SetNillableTokenExpiresAt sets the "token_expires_at" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableTokenExpiresAt(v *time.Time) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetTokenExpiresAt(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *UpstreamConnectionCreate) SetEnabled(v bool) *UpstreamConnectionCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableEnabled(v *bool) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// SetIntervalMinutes sets the "interval_minutes" field.
func (_c *UpstreamConnectionCreate) SetIntervalMinutes(v int) *UpstreamConnectionCreate {
	_c.mutation.SetIntervalMinutes(v)
	return _c
}

// SetNillableIntervalMinutes sets the "interval_minutes" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableIntervalMinutes(v *int) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetIntervalMinutes(*v)
	}
	return _c
}

// SetLastSyncAt sets the "last_sync_at" field.
func (_c *UpstreamConnectionCreate) SetLastSyncAt(v time.Time) *UpstreamConnectionCreate {
	_c.mutation.SetLastSyncAt(v)
	return _c
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableLastSyncAt(v *time.Time) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetLastSyncAt(*v)
	}
	return _c
}

// SetLastStatus sets the "last_status" field.
func (_c *UpstreamConnectionCreate) SetLastStatus(v string) *UpstreamConnectionCreate {
	_c.mutation.SetLastStatus(v)
	return _c
}

// SetNillableLastStatus sets the "last_status" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableLastStatus(v *string) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetLastStatus(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *UpstreamConnectionCreate) SetLastError(v string) *UpstreamConnectionCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableLastError(v *string) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetLastBalance sets the "last_balance" field.
func (_c *UpstreamConnectionCreate) SetLastBalance(v float64) *UpstreamConnectionCreate {
	_c.mutation.SetLastBalance(v)
	return _c
}

// SetNillableLastBalance sets the "last_balance" field if the given value is not nil.
func (_c *UpstreamConnectionCreate) SetNillableLastBalance(v *float64) *UpstreamConnectionCreate {
	if v != nil {
		_c.SetLastBalance(*v)
	}
	return _c
}

// AddSyncRunIDs adds the "sync_runs" edge to the UpstreamSyncRun entity by IDs.
func (_c *UpstreamConnectionCreate) AddSyncRunIDs(ids ...int64) *UpstreamConnectionCreate {
	_c.mutation.AddSyncRunIDs(ids...)
	return _c
}

// AddSyncRuns adds the "sync_runs" edges to the UpstreamSyncRun entity.
func (_c *UpstreamConnectionCreate) AddSyncRuns(v ...*UpstreamSyncRun) *UpstreamConnectionCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddSyncRunIDs(ids...)
}

// Mutation returns the UpstreamConnectionMutation object of the builder.
func (_c *UpstreamConnectionCreate) Mutation() *UpstreamConnectionMutation {
	return _c.mutation
}

// Save creates the UpstreamConnection in the database.
func (_c *UpstreamConnectionCreate) Save(ctx context.Context) (*UpstreamConnection, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamConnectionCreate) SaveX(ctx context.Context) *UpstreamConnection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamConnectionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamConnectionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamConnectionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := upstreamconnection.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := upstreamconnection.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := upstreamconnection.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
	if _, ok := _c.mutation.IntervalMinutes(); !ok {
		v := upstreamconnection.DefaultIntervalMinutes
		_c.mutation.SetIntervalMinutes(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamConnectionCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UpstreamConnection.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UpstreamConnection.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "UpstreamConnection.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := upstreamconnection.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.BaseURL(); !ok {
		return &ValidationError{Name: "base_url", err: errors.New(`ent: missing required field "UpstreamConnection.base_url"`)}
	}
	if v, ok := _c.mutation.BaseURL(); ok {
		if err := upstreamconnection.BaseURLValidator(v); err != nil {
			return &ValidationError{Name: "base_url", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.base_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AuthMode(); !ok {
		return &ValidationError{Name: "auth_mode", err: errors.New(`ent: missing required field "UpstreamConnection.auth_mode"`)}
	}
	if v, ok := _c.mutation.AuthMode(); ok {
		if err := upstreamconnection.AuthModeValidator(v); err != nil {
			return &ValidationError{Name: "auth_mode", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.auth_mode": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "UpstreamConnection.enabled"`)}
	}
	if _, ok := _c.mutation.IntervalMinutes(); !ok {
		return &ValidationError{Name: "interval_minutes", err: errors.New(`ent: missing required field "UpstreamConnection.interval_minutes"`)}
	}
	if v, ok := _c.mutation.LastStatus(); ok {
		if err := upstreamconnection.LastStatusValidator(v); err != nil {
			return &ValidationError{Name: "last_status", err: fmt.Errorf(`ent: validator failed for field "UpstreamConnection.last_status": %w`, err)}
		}
	}
	return nil
}

func (_c *UpstreamConnectionCreate) sqlSave(ctx context.Context) (*UpstreamConnection, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamConnectionCreate) createSpec() (*UpstreamConnection, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamConnection{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreamconnection.Table, sqlgraph.NewFieldSpec(upstreamconnection.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(upstreamconnection.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(upstreamconnection.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(upstreamconnection.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.BaseURL(); ok {
		_spec.SetField(upstreamconnection.FieldBaseURL, field.TypeString, value)
		_node.BaseURL = value
	}
	if value, ok := _c.mutation.AuthMode(); ok {
		_spec.SetField(upstreamconnection.FieldAuthMode, field.TypeEnum, value)
		_node.AuthMode = value
	}
	if value, ok := _c.mutation.CredentialsEncrypted(); ok {
		_spec.SetField(upstreamconnection.FieldCredentialsEncrypted, field.TypeString, value)
		_node.CredentialsEncrypted = value
	}
	if value, ok := _c.mutation.AccessTokenEncrypted(); ok {
		_spec.SetField(upstreamconnection.FieldAccessTokenEncrypted, field.TypeString, value)
		_node.AccessTokenEncrypted = value
	}
	if value, ok := _c.mutation.RefreshTokenEncrypted(); ok {
		_spec.SetField(upstreamconnection.FieldRefreshTokenEncrypted, field.TypeString, value)
		_node.RefreshTokenEncrypted = value
	}
	if value, ok := _c.mutation.TokenExpiresAt(); ok {
		_spec.SetField(upstreamconnection.FieldTokenExpiresAt, field.TypeTime, value)
		_node.TokenExpiresAt = &value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(upstreamconnection.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	if value, ok := _c.mutation.IntervalMinutes(); ok {
		_spec.SetField(upstreamconnection.FieldIntervalMinutes, field.TypeInt, value)
		_node.IntervalMinutes = value
	}
	if value, ok := _c.mutation.LastSyncAt(); ok {
		_spec.SetField(upstreamconnection.FieldLastSyncAt, field.TypeTime, value)
		_node.LastSyncAt = &value
	}
	if value, ok := _c.mutation.LastStatus(); ok {
		_spec.SetField(upstreamconnection.FieldLastStatus, field.TypeString, value)
		_node.LastStatus = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(upstreamconnection.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.LastBalance(); ok {
		_spec.SetField(upstreamconnection.FieldLastBalance, field.TypeFloat64, value)
		_node.LastBalance = &value
	}
	if nodes := _c.mutation.SyncRunsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   upstreamconnection.SyncRunsTable,
			Columns: []string{upstreamconnection.SyncRunsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamsyncrun.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamConnection.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamConnectionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamConnectionCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamConnectionUpsertOne {
	_c.conflict = opts
	return &UpstreamConnectionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamConnection.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamConnectionCreate) OnConflictColumns(columns ...string) *UpstreamConnectionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamConnectionUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamConnectionUpsertOne is the builder for "upsert"-ing
	//  one UpstreamConnection node.
	UpstreamConnectionUpsertOne struct {
		create *UpstreamConnectionCreate
	}

	// UpstreamConnectionUpsert is the "OnConflict" setter.
	UpstreamConnectionUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamConnectionUpsert) SetUpdatedAt(v time.Time) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateUpdatedAt() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *UpstreamConnectionUpsert) SetName(v string) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateName() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldName)
	return u
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamConnectionUpsert) SetBaseURL(v string) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldBaseURL, v)
	return u
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateBaseURL() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldBaseURL)
	return u
}

// SetAuthMode sets the "auth_mode" field.
func (u *UpstreamConnectionUpsert) SetAuthMode(v upstreamconnection.AuthMode) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldAuthMode, v)
	return u
}

// UpdateAuthMode sets the "auth_mode" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateAuthMode() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldAuthMode)
	return u
}

// SetCredentialsEncrypted sets the "credentials_encrypted" field.
func (u *UpstreamConnectionUpsert) SetCredentialsEncrypted(v string) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldCredentialsEncrypted, v)
	return u
}

// UpdateCredentialsEncrypted sets the "credentials_encrypted" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateCredentialsEncrypted() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldCredentialsEncrypted)
	return u
}

// ClearCredentialsEncrypted clears the value of the "credentials_encrypted" field.
func (u *UpstreamConnectionUpsert) ClearCredentialsEncrypted() *UpstreamConnectionUpsert {
	u.SetNull(upstreamconnection.FieldCredentialsEncrypted)
	return u
}

// SetAccessTokenEncrypted sets the "access_token_encrypted" field.
func (u *UpstreamConnectionUpsert) SetAccessTokenEncrypted(v string) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldAccessTokenEncrypted, v)
	return u
}

// UpdateAccessTokenEncrypted sets the "access_token_encrypted" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateAccessTokenEncrypted() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldAccessTokenEncrypted)
	return u
}

// ClearAccessTokenEncrypted clears the value of the "access_token_encrypted" field.
func (u *UpstreamConnectionUpsert) ClearAccessTokenEncrypted() *UpstreamConnectionUpsert {
	u.SetNull(upstreamconnection.FieldAccessTokenEncrypted)
	return u
}

// SetRefreshTokenEncrypted sets the "refresh_token_encrypted" field.
func (u *UpstreamConnectionUpsert) SetRefreshTokenEncrypted(v string) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldRefreshTokenEncrypted, v)
	return u
}

// UpdateRefreshTokenEncrypted sets the "refresh_token_encrypted" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateRefreshTokenEncrypted() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldRefreshTokenEncrypted)
	return u
}

// ClearRefreshTokenEncrypted clears the value of the "refresh_token_encrypted" field.
func (u *UpstreamConnectionUpsert) ClearRefreshTokenEncrypted() *UpstreamConnectionUpsert {
	u.SetNull(upstreamconnection.FieldRefreshTokenEncrypted)
	return u
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (u *UpstreamConnectionUpsert) SetTokenExpiresAt(v time.Time) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldTokenExpiresAt, v)
	return u
}

// UpdateTokenExpiresAt sets the "token_expires_at" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateTokenExpiresAt() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldTokenExpiresAt)
	return u
}

// ClearTokenExpiresAt clears the value of the "token_expires_at" field.
func (u *UpstreamConnectionUpsert) ClearTokenExpiresAt() *UpstreamConnectionUpsert {
	u.SetNull(upstreamconnection.FieldTokenExpiresAt)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamConnectionUpsert) SetEnabled(v bool) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateEnabled() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldEnabled)
	return u
}

// SetIntervalMinutes sets the "interval_minutes" field.
func (u *UpstreamConnectionUpsert) SetIntervalMinutes(v int) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldIntervalMinutes, v)
	return u
}

// UpdateIntervalMinutes sets the "interval_minutes" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateIntervalMinutes() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldIntervalMinutes)
	return u
}

// AddIntervalMinutes adds v to the "interval_minutes" field.
func (u *UpstreamConnectionUpsert) AddIntervalMinutes(v int) *UpstreamConnectionUpsert {
	u.Add(upstreamconnection.FieldIntervalMinutes, v)
	return u
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *UpstreamConnectionUpsert) SetLastSyncAt(v time.Time) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldLastSyncAt, v)
	return u
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateLastSyncAt() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldLastSyncAt)
	return u
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *UpstreamConnectionUpsert) ClearLastSyncAt() *UpstreamConnectionUpsert {
	u.SetNull(upstreamconnection.FieldLastSyncAt)
	return u
}

// SetLastStatus sets the "last_status" field.
func (u *UpstreamConnectionUpsert) SetLastStatus(v string) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldLastStatus, v)
	return u
}

// UpdateLastStatus sets the "last_status" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateLastStatus() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldLastStatus)
	return u
}

// ClearLastStatus clears the value of the "last_status" field.
func (u *UpstreamConnectionUpsert) ClearLastStatus() *UpstreamConnectionUpsert {
	u.SetNull(upstreamconnection.FieldLastStatus)
	return u
}

// SetLastError sets the "last_error" field.
func (u *UpstreamConnectionUpsert) SetLastError(v string) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldLastError, v)
	return u
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateLastError() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldLastError)
	return u
}

// ClearLastError clears the value of the "last_error" field.
func (u *UpstreamConnectionUpsert) ClearLastError() *UpstreamConnectionUpsert {
	u.SetNull(upstreamconnection.FieldLastError)
	return u
}

// SetLastBalance sets the "last_balance" field.
func (u *UpstreamConnectionUpsert) SetLastBalance(v float64) *UpstreamConnectionUpsert {
	u.Set(upstreamconnection.FieldLastBalance, v)
	return u
}

// UpdateLastBalance sets the "last_balance" field to the value that was provided on create.
func (u *UpstreamConnectionUpsert) UpdateLastBalance() *UpstreamConnectionUpsert {
	u.SetExcluded(upstreamconnection.FieldLastBalance)
	return u
}

// AddLastBalance adds v to the "last_balance" field.
func (u *UpstreamConnectionUpsert) AddLastBalance(v float64) *UpstreamConnectionUpsert {
	u.Add(upstreamconnection.FieldLastBalance, v)
	return u
}

// ClearLastBalance clears the value of the "last_balance" field.
func (u *UpstreamConnectionUpsert) ClearLastBalance() *UpstreamConnectionUpsert {
	u.SetNull(upstreamconnection.FieldLastBalance)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamConnection.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamConnectionUpsertOne) UpdateNewValues() *UpstreamConnectionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(upstreamconnection.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamConnection.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamConnectionUpsertOne) Ignore() *UpstreamConnectionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamConnectionUpsertOne) DoNothing() *UpstreamConnectionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamConnectionCreate.OnConflict
// documentation for more info.
func (u *UpstreamConnectionUpsertOne) Update(set func(*UpstreamConnectionUpsert)) *UpstreamConnectionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamConnectionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamConnectionUpsertOne) SetUpdatedAt(v time.Time) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateUpdatedAt() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *UpstreamConnectionUpsertOne) SetName(v string) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateName() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateName()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamConnectionUpsertOne) SetBaseURL(v string) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateBaseURL() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateBaseURL()
	})
}

// SetAuthMode sets the "auth_mode" field.
func (u *UpstreamConnectionUpsertOne) SetAuthMode(v upstreamconnection.AuthMode) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetAuthMode(v)
	})
}

// UpdateAuthMode sets the "auth_mode" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateAuthMode() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateAuthMode()
	})
}

// SetCredentialsEncrypted sets the "credentials_encrypted" field.
func (u *UpstreamConnectionUpsertOne) SetCredentialsEncrypted(v string) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetCredentialsEncrypted(v)
	})
}

// UpdateCredentialsEncrypted sets the "credentials_encrypted" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateCredentialsEncrypted() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateCredentialsEncrypted()
	})
}

// ClearCredentialsEncrypted clears the value of the "credentials_encrypted" field.
func (u *UpstreamConnectionUpsertOne) ClearCredentialsEncrypted() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearCredentialsEncrypted()
	})
}

// SetAccessTokenEncrypted sets the "access_token_encrypted" field.
func (u *UpstreamConnectionUpsertOne) SetAccessTokenEncrypted(v string) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetAccessTokenEncrypted(v)
	})
}

// UpdateAccessTokenEncrypted sets the "access_token_encrypted" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateAccessTokenEncrypted() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateAccessTokenEncrypted()
	})
}

// ClearAccessTokenEncrypted clears the value of the "access_token_encrypted" field.
func (u *UpstreamConnectionUpsertOne) ClearAccessTokenEncrypted() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearAccessTokenEncrypted()
	})
}

// SetRefreshTokenEncrypted sets the "refresh_token_encrypted" field.
func (u *UpstreamConnectionUpsertOne) SetRefreshTokenEncrypted(v string) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetRefreshTokenEncrypted(v)
	})
}

// UpdateRefreshTokenEncrypted sets the "refresh_token_encrypted" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateRefreshTokenEncrypted() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateRefreshTokenEncrypted()
	})
}

// ClearRefreshTokenEncrypted clears the value of the "refresh_token_encrypted" field.
func (u *UpstreamConnectionUpsertOne) ClearRefreshTokenEncrypted() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearRefreshTokenEncrypted()
	})
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (u *UpstreamConnectionUpsertOne) SetTokenExpiresAt(v time.Time) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetTokenExpiresAt(v)
	})
}

// UpdateTokenExpiresAt sets the "token_expires_at" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateTokenExpiresAt() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateTokenExpiresAt()
	})
}

// ClearTokenExpiresAt clears the value of the "token_expires_at" field.
func (u *UpstreamConnectionUpsertOne) ClearTokenExpiresAt() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearTokenExpiresAt()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamConnectionUpsertOne) SetEnabled(v bool) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateEnabled() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateEnabled()
	})
}

// SetIntervalMinutes sets the "interval_minutes" field.
func (u *UpstreamConnectionUpsertOne) SetIntervalMinutes(v int) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetIntervalMinutes(v)
	})
}

// AddIntervalMinutes adds v to the "interval_minutes" field.
func (u *UpstreamConnectionUpsertOne) AddIntervalMinutes(v int) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.AddIntervalMinutes(v)
	})
}

// UpdateIntervalMinutes sets the "interval_minutes" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateIntervalMinutes() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateIntervalMinutes()
	})
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *UpstreamConnectionUpsertOne) SetLastSyncAt(v time.Time) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetLastSyncAt(v)
	})
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateLastSyncAt() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateLastSyncAt()
	})
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *UpstreamConnectionUpsertOne) ClearLastSyncAt() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearLastSyncAt()
	})
}

// SetLastStatus sets the "last_status" field.
func (u *UpstreamConnectionUpsertOne) SetLastStatus(v string) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetLastStatus(v)
	})
}

// UpdateLastStatus sets the "last_status" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateLastStatus() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateLastStatus()
	})
}

// ClearLastStatus clears the value of the "last_status" field.
func (u *UpstreamConnectionUpsertOne) ClearLastStatus() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearLastStatus()
	})
}

// SetLastError sets the "last_error" field.
func (u *UpstreamConnectionUpsertOne) SetLastError(v string) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateLastError() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *UpstreamConnectionUpsertOne) ClearLastError() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearLastError()
	})
}

// SetLastBalance sets the "last_balance" field.
func (u *UpstreamConnectionUpsertOne) SetLastBalance(v float64) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetLastBalance(v)
	})
}

// AddLastBalance adds v to the "last_balance" field.
func (u *UpstreamConnectionUpsertOne) AddLastBalance(v float64) *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.AddLastBalance(v)
	})
}

// UpdateLastBalance sets the "last_balance" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertOne) UpdateLastBalance() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateLastBalance()
	})
}

// ClearLastBalance clears the value of the "last_balance" field.
func (u *UpstreamConnectionUpsertOne) ClearLastBalance() *UpstreamConnectionUpsertOne {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearLastBalance()
	})
}

// Exec executes the query.
func (u *UpstreamConnectionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamConnectionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamConnectionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamConnectionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamConnectionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamConnectionCreateBulk is the builder for creating many UpstreamConnection entities in bulk.
type UpstreamConnectionCreateBulk struct {
	config
	err      error
	builders []*UpstreamConnectionCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamConnection entities in the database.
func (_c *UpstreamConnectionCreateBulk) Save(ctx context.Context) ([]*UpstreamConnection, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamConnection, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamConnectionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamConnectionCreateBulk) SaveX(ctx context.Context) []*UpstreamConnection {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamConnectionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamConnectionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamConnection.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamConnectionUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamConnectionCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamConnectionUpsertBulk {
	_c.conflict = opts
	return &UpstreamConnectionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamConnection.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamConnectionCreateBulk) OnConflictColumns(columns ...string) *UpstreamConnectionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamConnectionUpsertBulk{
		create: _c,
	}
}

// UpstreamConnectionUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamConnection nodes.
type UpstreamConnectionUpsertBulk struct {
	create *UpstreamConnectionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamConnection.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamConnectionUpsertBulk) UpdateNewValues() *UpstreamConnectionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(upstreamconnection.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamConnection.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamConnectionUpsertBulk) Ignore() *UpstreamConnectionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamConnectionUpsertBulk) DoNothing() *UpstreamConnectionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamConnectionCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamConnectionUpsertBulk) Update(set func(*UpstreamConnectionUpsert)) *UpstreamConnectionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamConnectionUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *UpstreamConnectionUpsertBulk) SetUpdatedAt(v time.Time) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateUpdatedAt() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *UpstreamConnectionUpsertBulk) SetName(v string) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateName() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateName()
	})
}

// SetBaseURL sets the "base_url" field.
func (u *UpstreamConnectionUpsertBulk) SetBaseURL(v string) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetBaseURL(v)
	})
}

// UpdateBaseURL sets the "base_url" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateBaseURL() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateBaseURL()
	})
}

// SetAuthMode sets the "auth_mode" field.
func (u *UpstreamConnectionUpsertBulk) SetAuthMode(v upstreamconnection.AuthMode) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetAuthMode(v)
	})
}

// UpdateAuthMode sets the "auth_mode" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateAuthMode() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateAuthMode()
	})
}

// SetCredentialsEncrypted sets the "credentials_encrypted" field.
func (u *UpstreamConnectionUpsertBulk) SetCredentialsEncrypted(v string) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetCredentialsEncrypted(v)
	})
}

// UpdateCredentialsEncrypted sets the "credentials_encrypted" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateCredentialsEncrypted() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateCredentialsEncrypted()
	})
}

// ClearCredentialsEncrypted clears the value of the "credentials_encrypted" field.
func (u *UpstreamConnectionUpsertBulk) ClearCredentialsEncrypted() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearCredentialsEncrypted()
	})
}

// SetAccessTokenEncrypted sets the "access_token_encrypted" field.
func (u *UpstreamConnectionUpsertBulk) SetAccessTokenEncrypted(v string) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetAccessTokenEncrypted(v)
	})
}

// UpdateAccessTokenEncrypted sets the "access_token_encrypted" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateAccessTokenEncrypted() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateAccessTokenEncrypted()
	})
}

// ClearAccessTokenEncrypted clears the value of the "access_token_encrypted" field.
func (u *UpstreamConnectionUpsertBulk) ClearAccessTokenEncrypted() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearAccessTokenEncrypted()
	})
}

// SetRefreshTokenEncrypted sets the "refresh_token_encrypted" field.
func (u *UpstreamConnectionUpsertBulk) SetRefreshTokenEncrypted(v string) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetRefreshTokenEncrypted(v)
	})
}

// UpdateRefreshTokenEncrypted sets the "refresh_token_encrypted" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateRefreshTokenEncrypted() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateRefreshTokenEncrypted()
	})
}

// ClearRefreshTokenEncrypted clears the value of the "refresh_token_encrypted" field.
func (u *UpstreamConnectionUpsertBulk) ClearRefreshTokenEncrypted() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearRefreshTokenEncrypted()
	})
}

// SetTokenExpiresAt sets the "token_expires_at" field.
func (u *UpstreamConnectionUpsertBulk) SetTokenExpiresAt(v time.Time) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetTokenExpiresAt(v)
	})
}

// UpdateTokenExpiresAt sets the "token_expires_at" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateTokenExpiresAt() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateTokenExpiresAt()
	})
}

// ClearTokenExpiresAt clears the value of the "token_expires_at" field.
func (u *UpstreamConnectionUpsertBulk) ClearTokenExpiresAt() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearTokenExpiresAt()
	})
}

// SetEnabled sets the "enabled" field.
func (u *UpstreamConnectionUpsertBulk) SetEnabled(v bool) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateEnabled() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateEnabled()
	})
}

// SetIntervalMinutes sets the "interval_minutes" field.
func (u *UpstreamConnectionUpsertBulk) SetIntervalMinutes(v int) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetIntervalMinutes(v)
	})
}

// AddIntervalMinutes adds v to the "interval_minutes" field.
func (u *UpstreamConnectionUpsertBulk) AddIntervalMinutes(v int) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.AddIntervalMinutes(v)
	})
}

// UpdateIntervalMinutes sets the "interval_minutes" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateIntervalMinutes() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateIntervalMinutes()
	})
}

// SetLastSyncAt sets the "last_sync_at" field.
func (u *UpstreamConnectionUpsertBulk) SetLastSyncAt(v time.Time) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetLastSyncAt(v)
	})
}

// UpdateLastSyncAt sets the "last_sync_at" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateLastSyncAt() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateLastSyncAt()
	})
}

// ClearLastSyncAt clears the value of the "last_sync_at" field.
func (u *UpstreamConnectionUpsertBulk) ClearLastSyncAt() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearLastSyncAt()
	})
}

// SetLastStatus sets the "last_status" field.
func (u *UpstreamConnectionUpsertBulk) SetLastStatus(v string) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetLastStatus(v)
	})
}

// UpdateLastStatus sets the "last_status" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateLastStatus() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateLastStatus()
	})
}

// ClearLastStatus clears the value of the "last_status" field.
func (u *UpstreamConnectionUpsertBulk) ClearLastStatus() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearLastStatus()
	})
}

// SetLastError sets the "last_error" field.
func (u *UpstreamConnectionUpsertBulk) SetLastError(v string) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetLastError(v)
	})
}

// UpdateLastError sets the "last_error" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateLastError() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateLastError()
	})
}

// ClearLastError clears the value of the "last_error" field.
func (u *UpstreamConnectionUpsertBulk) ClearLastError() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearLastError()
	})
}

// SetLastBalance sets the "last_balance" field.
func (u *UpstreamConnectionUpsertBulk) SetLastBalance(v float64) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.SetLastBalance(v)
	})
}

// AddLastBalance adds v to the "last_balance" field.
func (u *UpstreamConnectionUpsertBulk) AddLastBalance(v float64) *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.AddLastBalance(v)
	})
}

// UpdateLastBalance sets the "last_balance" field to the value that was provided on create.
func (u *UpstreamConnectionUpsertBulk) UpdateLastBalance() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.UpdateLastBalance()
	})
}

// ClearLastBalance clears the value of the "last_balance" field.
func (u *UpstreamConnectionUpsertBulk) ClearLastBalance() *UpstreamConnectionUpsertBulk {
	return u.Update(func(s *UpstreamConnectionUpsert) {
		s.ClearLastBalance()
	})
}

// Exec executes the query.
func (u *UpstreamConnectionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamConnectionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamConnectionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamConnectionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
