// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconnection"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsyncrun"
	"github.com/Wei-Shaw/sub2api/internal/service/upstreamratesync"
)

// UpstreamSyncRunCreate is the builder for creating a UpstreamSyncRun entity.
type UpstreamSyncRunCreate struct {
	config
	mutation *UpstreamSyncRunMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetConnectionID sets the "connection_id" field.
func (_c *UpstreamSyncRunCreate) SetConnectionID(v int64) *UpstreamSyncRunCreate {
	_c.mutation.SetConnectionID(v)
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *UpstreamSyncRunCreate) SetStartedAt(v time.Time) *UpstreamSyncRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *UpstreamSyncRunCreate) SetNillableStartedAt(v *time.Time) *UpstreamSyncRunCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetFinishedAt sets the "finished_at" field.
func (_c *UpstreamSyncRunCreate) SetFinishedAt(v time.Time) *UpstreamSyncRunCreate {
	_c.mutation.SetFinishedAt(v)
	return _c
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_c *UpstreamSyncRunCreate) SetNillableFinishedAt(v *time.Time) *UpstreamSyncRunCreate {
	if v != nil {
		_c.SetFinishedAt(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *UpstreamSyncRunCreate) SetStatus(v upstreamsyncrun.Status) *UpstreamSyncRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *UpstreamSyncRunCreate) SetNillableStatus(v *upstreamsyncrun.Status) *UpstreamSyncRunCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetKeysFetched sets the "keys_fetched" field.
func (_c *UpstreamSyncRunCreate) SetKeysFetched(v int) *UpstreamSyncRunCreate {
	_c.mutation.SetKeysFetched(v)
	return _c
}

// SetNillableKeysFetched sets the "keys_fetched" field if the given value is not nil.
func (_c *UpstreamSyncRunCreate) SetNillableKeysFetched(v *int) *UpstreamSyncRunCreate {
	if v != nil {
		_c.SetKeysFetched(*v)
	}
	return _c
}

// SetAccountsMatched sets the "accounts_matched" field.
func (_c *UpstreamSyncRunCreate) SetAccountsMatched(v int) *UpstreamSyncRunCreate {
	_c.mutation.SetAccountsMatched(v)
	return _c
}

// SetNillableAccountsMatched sets the "accounts_matched" field if the given value is not nil.
func (_c *UpstreamSyncRunCreate) SetNillableAccountsMatched(v *int) *UpstreamSyncRunCreate {
	if v != nil {
		_c.SetAccountsMatched(*v)
	}
	return _c
}

// SetAccountsUpdated sets the "accounts_updated" field.
func (_c *UpstreamSyncRunCreate) SetAccountsUpdated(v int) *UpstreamSyncRunCreate {
	_c.mutation.SetAccountsUpdated(v)
	return _c
}

// SetNillableAccountsUpdated sets the "accounts_updated" field if the given value is not nil.
func (_c *UpstreamSyncRunCreate) SetNillableAccountsUpdated(v *int) *UpstreamSyncRunCreate {
	if v != nil {
		_c.SetAccountsUpdated(*v)
	}
	return _c
}

// SetAccountsUnchanged sets the "accounts_unchanged" field.
func (_c *UpstreamSyncRunCreate) SetAccountsUnchanged(v int) *UpstreamSyncRunCreate {
	_c.mutation.SetAccountsUnchanged(v)
	return _c
}

// SetNillableAccountsUnchanged sets the "accounts_unchanged" field if the given value is not nil.
func (_c *UpstreamSyncRunCreate) SetNillableAccountsUnchanged(v *int) *UpstreamSyncRunCreate {
	if v != nil {
		_c.SetAccountsUnchanged(*v)
	}
	return _c
}

// SetAccountsUnmatched sets the "accounts_unmatched" field.
func (_c *UpstreamSyncRunCreate) SetAccountsUnmatched(v int) *UpstreamSyncRunCreate {
	_c.mutation.SetAccountsUnmatched(v)
	return _c
}

// SetNillableAccountsUnmatched sets the "accounts_unmatched" field if the given value is not nil.
func (_c *UpstreamSyncRunCreate) SetNillableAccountsUnmatched(v *int) *UpstreamSyncRunCreate {
	if v != nil {
		_c.SetAccountsUnmatched(*v)
	}
	return _c
}

// SetDetails sets the "details" field.
func (_c *UpstreamSyncRunCreate) SetDetails(v []upstreamratesync.SyncRunDetail) *UpstreamSyncRunCreate {
	_c.mutation.SetDetails(v)
	return _c
}

// SetError sets the "error" field.
func (_c *UpstreamSyncRunCreate) SetError(v string) *UpstreamSyncRunCreate {
	_c.mutation.SetError(v)
	return _c
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_c *UpstreamSyncRunCreate) SetNillableError(v *string) *UpstreamSyncRunCreate {
	if v != nil {
		_c.SetError(*v)
	}
	return _c
}

// SetConnection sets the "connection" edge to the UpstreamConnection entity.
func (_c *UpstreamSyncRunCreate) SetConnection(v *UpstreamConnection) *UpstreamSyncRunCreate {
	return _c.SetConnectionID(v.ID)
}

// Mutation returns the UpstreamSyncRunMutation object of the builder.
func (_c *UpstreamSyncRunCreate) Mutation() *UpstreamSyncRunMutation {
	return _c.mutation
}

// Save creates the UpstreamSyncRun in the database.
func (_c *UpstreamSyncRunCreate) Save(ctx context.Context) (*UpstreamSyncRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UpstreamSyncRunCreate) SaveX(ctx context.Context) *UpstreamSyncRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamSyncRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamSyncRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UpstreamSyncRunCreate) defaults() {
	if _, ok := _c.mutation.StartedAt(); !ok {
		v := upstreamsyncrun.DefaultStartedAt()
		_c.mutation.SetStartedAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := upstreamsyncrun.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.KeysFetched(); !ok {
		v := upstreamsyncrun.DefaultKeysFetched
		_c.mutation.SetKeysFetched(v)
	}
	if _, ok := _c.mutation.AccountsMatched(); !ok {
		v := upstreamsyncrun.DefaultAccountsMatched
		_c.mutation.SetAccountsMatched(v)
	}
	if _, ok := _c.mutation.AccountsUpdated(); !ok {
		v := upstreamsyncrun.DefaultAccountsUpdated
		_c.mutation.SetAccountsUpdated(v)
	}
	if _, ok := _c.mutation.AccountsUnchanged(); !ok {
		v := upstreamsyncrun.DefaultAccountsUnchanged
		_c.mutation.SetAccountsUnchanged(v)
	}
	if _, ok := _c.mutation.AccountsUnmatched(); !ok {
		v := upstreamsyncrun.DefaultAccountsUnmatched
		_c.mutation.SetAccountsUnmatched(v)
	}
	if _, ok := _c.mutation.Details(); !ok {
		v := upstreamsyncrun.DefaultDetails
		_c.mutation.SetDetails(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UpstreamSyncRunCreate) check() error {
	if _, ok := _c.mutation.ConnectionID(); !ok {
		return &ValidationError{Name: "connection_id", err: errors.New(`ent: missing required field "UpstreamSyncRun.connection_id"`)}
	}
	if _, ok := _c.mutation.StartedAt(); !ok {
		return &ValidationError{Name: "started_at", err: errors.New(`ent: missing required field "UpstreamSyncRun.started_at"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "UpstreamSyncRun.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := upstreamsyncrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeysFetched(); !ok {
		return &ValidationError{Name: "keys_fetched", err: errors.New(`ent: missing required field "UpstreamSyncRun.keys_fetched"`)}
	}
	if v, ok := _c.mutation.KeysFetched(); ok {
		if err := upstreamsyncrun.KeysFetchedValidator(v); err != nil {
			return &ValidationError{Name: "keys_fetched", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.keys_fetched": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountsMatched(); !ok {
		return &ValidationError{Name: "accounts_matched", err: errors.New(`ent: missing required field "UpstreamSyncRun.accounts_matched"`)}
	}
	if v, ok := _c.mutation.AccountsMatched(); ok {
		if err := upstreamsyncrun.AccountsMatchedValidator(v); err != nil {
			return &ValidationError{Name: "accounts_matched", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.accounts_matched": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountsUpdated(); !ok {
		return &ValidationError{Name: "accounts_updated", err: errors.New(`ent: missing required field "UpstreamSyncRun.accounts_updated"`)}
	}
	if v, ok := _c.mutation.AccountsUpdated(); ok {
		if err := upstreamsyncrun.AccountsUpdatedValidator(v); err != nil {
			return &ValidationError{Name: "accounts_updated", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.accounts_updated": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountsUnchanged(); !ok {
		return &ValidationError{Name: "accounts_unchanged", err: errors.New(`ent: missing required field "UpstreamSyncRun.accounts_unchanged"`)}
	}
	if v, ok := _c.mutation.AccountsUnchanged(); ok {
		if err := upstreamsyncrun.AccountsUnchangedValidator(v); err != nil {
			return &ValidationError{Name: "accounts_unchanged", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.accounts_unchanged": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AccountsUnmatched(); !ok {
		return &ValidationError{Name: "accounts_unmatched", err: errors.New(`ent: missing required field "UpstreamSyncRun.accounts_unmatched"`)}
	}
	if v, ok := _c.mutation.AccountsUnmatched(); ok {
		if err := upstreamsyncrun.AccountsUnmatchedValidator(v); err != nil {
			return &ValidationError{Name: "accounts_unmatched", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.accounts_unmatched": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Details(); !ok {
		return &ValidationError{Name: "details", err: errors.New(`ent: missing required field "UpstreamSyncRun.details"`)}
	}
	if len(_c.mutation.ConnectionIDs()) == 0 {
		return &ValidationError{Name: "connection", err: errors.New(`ent: missing required edge "UpstreamSyncRun.connection"`)}
	}
	return nil
}

func (_c *UpstreamSyncRunCreate) sqlSave(ctx context.Context) (*UpstreamSyncRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UpstreamSyncRunCreate) createSpec() (*UpstreamSyncRun, *sqlgraph.CreateSpec) {
	var (
		_node = &UpstreamSyncRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(upstreamsyncrun.Table, sqlgraph.NewFieldSpec(upstreamsyncrun.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(upstreamsyncrun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = value
	}
	if value, ok := _c.mutation.FinishedAt(); ok {
		_spec.SetField(upstreamsyncrun.FieldFinishedAt, field.TypeTime, value)
		_node.FinishedAt = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(upstreamsyncrun.FieldStatus, field.TypeEnum, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.KeysFetched(); ok {
		_spec.SetField(upstreamsyncrun.FieldKeysFetched, field.TypeInt, value)
		_node.KeysFetched = value
	}
	if value, ok := _c.mutation.AccountsMatched(); ok {
		_spec.SetField(upstreamsyncrun.FieldAccountsMatched, field.TypeInt, value)
		_node.AccountsMatched = value
	}
	if value, ok := _c.mutation.AccountsUpdated(); ok {
		_spec.SetField(upstreamsyncrun.FieldAccountsUpdated, field.TypeInt, value)
		_node.AccountsUpdated = value
	}
	if value, ok := _c.mutation.AccountsUnchanged(); ok {
		_spec.SetField(upstreamsyncrun.FieldAccountsUnchanged, field.TypeInt, value)
		_node.AccountsUnchanged = value
	}
	if value, ok := _c.mutation.AccountsUnmatched(); ok {
		_spec.SetField(upstreamsyncrun.FieldAccountsUnmatched, field.TypeInt, value)
		_node.AccountsUnmatched = value
	}
	if value, ok := _c.mutation.Details(); ok {
		_spec.SetField(upstreamsyncrun.FieldDetails, field.TypeJSON, value)
		_node.Details = value
	}
	if value, ok := _c.mutation.Error(); ok {
		_spec.SetField(upstreamsyncrun.FieldError, field.TypeString, value)
		_node.Error = value
	}
	if nodes := _c.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamsyncrun.ConnectionTable,
			Columns: []string{upstreamsyncrun.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamconnection.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ConnectionID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamSyncRun.Create().
//		SetConnectionID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamSyncRunUpsert) {
//			SetConnectionID(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamSyncRunCreate) OnConflict(opts ...sql.ConflictOption) *UpstreamSyncRunUpsertOne {
	_c.conflict = opts
	return &UpstreamSyncRunUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamSyncRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamSyncRunCreate) OnConflictColumns(columns ...string) *UpstreamSyncRunUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamSyncRunUpsertOne{
		create: _c,
	}
}

type (
	// UpstreamSyncRunUpsertOne is the builder for "upsert"-ing
	//  one UpstreamSyncRun node.
	UpstreamSyncRunUpsertOne struct {
		create *UpstreamSyncRunCreate
	}

	// UpstreamSyncRunUpsert is the "OnConflict" setter.
	UpstreamSyncRunUpsert struct {
		*sql.UpdateSet
	}
)

// SetConnectionID sets the "connection_id" field.
func (u *UpstreamSyncRunUpsert) SetConnectionID(v int64) *UpstreamSyncRunUpsert {
	u.Set(upstreamsyncrun.FieldConnectionID, v)
	return u
}

// UpdateConnectionID sets the "connection_id" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsert) UpdateConnectionID() *UpstreamSyncRunUpsert {
	u.SetExcluded(upstreamsyncrun.FieldConnectionID)
	return u
}

// SetFinishedAt sets the "finished_at" field.
func (u *UpstreamSyncRunUpsert) SetFinishedAt(v time.Time) *UpstreamSyncRunUpsert {
	u.Set(upstreamsyncrun.FieldFinishedAt, v)
	return u
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsert) UpdateFinishedAt() *UpstreamSyncRunUpsert {
	u.SetExcluded(upstreamsyncrun.FieldFinishedAt)
	return u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *UpstreamSyncRunUpsert) ClearFinishedAt() *UpstreamSyncRunUpsert {
	u.SetNull(upstreamsyncrun.FieldFinishedAt)
	return u
}

// SetStatus sets the "status" field.
func (u *UpstreamSyncRunUpsert) SetStatus(v upstreamsyncrun.Status) *UpstreamSyncRunUpsert {
	u.Set(upstreamsyncrun.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsert) UpdateStatus() *UpstreamSyncRunUpsert {
	u.SetExcluded(upstreamsyncrun.FieldStatus)
	return u
}

// SetKeysFetched sets the "keys_fetched" field.
func (u *UpstreamSyncRunUpsert) SetKeysFetched(v int) *UpstreamSyncRunUpsert {
	u.Set(upstreamsyncrun.FieldKeysFetched, v)
	return u
}

// UpdateKeysFetched sets the "keys_fetched" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsert) UpdateKeysFetched() *UpstreamSyncRunUpsert {
	u.SetExcluded(upstreamsyncrun.FieldKeysFetched)
	return u
}

// AddKeysFetched adds v to the "keys_fetched" field.
func (u *UpstreamSyncRunUpsert) AddKeysFetched(v int) *UpstreamSyncRunUpsert {
	u.Add(upstreamsyncrun.FieldKeysFetched, v)
	return u
}

// SetAccountsMatched sets the "accounts_matched" field.
func (u *UpstreamSyncRunUpsert) SetAccountsMatched(v int) *UpstreamSyncRunUpsert {
	u.Set(upstreamsyncrun.FieldAccountsMatched, v)
	return u
}

// UpdateAccountsMatched sets the "accounts_matched" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsert) UpdateAccountsMatched() *UpstreamSyncRunUpsert {
	u.SetExcluded(upstreamsyncrun.FieldAccountsMatched)
	return u
}

// AddAccountsMatched adds v to the "accounts_matched" field.
func (u *UpstreamSyncRunUpsert) AddAccountsMatched(v int) *UpstreamSyncRunUpsert {
	u.Add(upstreamsyncrun.FieldAccountsMatched, v)
	return u
}

// SetAccountsUpdated sets the "accounts_updated" field.
func (u *UpstreamSyncRunUpsert) SetAccountsUpdated(v int) *UpstreamSyncRunUpsert {
	u.Set(upstreamsyncrun.FieldAccountsUpdated, v)
	return u
}

// UpdateAccountsUpdated sets the "accounts_updated" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsert) UpdateAccountsUpdated() *UpstreamSyncRunUpsert {
	u.SetExcluded(upstreamsyncrun.FieldAccountsUpdated)
	return u
}

// AddAccountsUpdated adds v to the "accounts_updated" field.
func (u *UpstreamSyncRunUpsert) AddAccountsUpdated(v int) *UpstreamSyncRunUpsert {
	u.Add(upstreamsyncrun.FieldAccountsUpdated, v)
	return u
}

// SetAccountsUnchanged sets the "accounts_unchanged" field.
func (u *UpstreamSyncRunUpsert) SetAccountsUnchanged(v int) *UpstreamSyncRunUpsert {
	u.Set(upstreamsyncrun.FieldAccountsUnchanged, v)
	return u
}

// UpdateAccountsUnchanged sets the "accounts_unchanged" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsert) UpdateAccountsUnchanged() *UpstreamSyncRunUpsert {
	u.SetExcluded(upstreamsyncrun.FieldAccountsUnchanged)
	return u
}

// AddAccountsUnchanged adds v to the "accounts_unchanged" field.
func (u *UpstreamSyncRunUpsert) AddAccountsUnchanged(v int) *UpstreamSyncRunUpsert {
	u.Add(upstreamsyncrun.FieldAccountsUnchanged, v)
	return u
}

// SetAccountsUnmatched sets the "accounts_unmatched" field.
func (u *UpstreamSyncRunUpsert) SetAccountsUnmatched(v int) *UpstreamSyncRunUpsert {
	u.Set(upstreamsyncrun.FieldAccountsUnmatched, v)
	return u
}

// UpdateAccountsUnmatched sets the "accounts_unmatched" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsert) UpdateAccountsUnmatched() *UpstreamSyncRunUpsert {
	u.SetExcluded(upstreamsyncrun.FieldAccountsUnmatched)
	return u
}

// AddAccountsUnmatched adds v to the "accounts_unmatched" field.
func (u *UpstreamSyncRunUpsert) AddAccountsUnmatched(v int) *UpstreamSyncRunUpsert {
	u.Add(upstreamsyncrun.FieldAccountsUnmatched, v)
	return u
}

// SetDetails sets the "details" field.
func (u *UpstreamSyncRunUpsert) SetDetails(v []upstreamratesync.SyncRunDetail) *UpstreamSyncRunUpsert {
	u.Set(upstreamsyncrun.FieldDetails, v)
	return u
}

// UpdateDetails sets the "details" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsert) UpdateDetails() *UpstreamSyncRunUpsert {
	u.SetExcluded(upstreamsyncrun.FieldDetails)
	return u
}

// SetError sets the "error" field.
func (u *UpstreamSyncRunUpsert) SetError(v string) *UpstreamSyncRunUpsert {
	u.Set(upstreamsyncrun.FieldError, v)
	return u
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsert) UpdateError() *UpstreamSyncRunUpsert {
	u.SetExcluded(upstreamsyncrun.FieldError)
	return u
}

// ClearError clears the value of the "error" field.
func (u *UpstreamSyncRunUpsert) ClearError() *UpstreamSyncRunUpsert {
	u.SetNull(upstreamsyncrun.FieldError)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.UpstreamSyncRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamSyncRunUpsertOne) UpdateNewValues() *UpstreamSyncRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.StartedAt(); exists {
			s.SetIgnore(upstreamsyncrun.FieldStartedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamSyncRun.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *UpstreamSyncRunUpsertOne) Ignore() *UpstreamSyncRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamSyncRunUpsertOne) DoNothing() *UpstreamSyncRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamSyncRunCreate.OnConflict
// documentation for more info.
func (u *UpstreamSyncRunUpsertOne) Update(set func(*UpstreamSyncRunUpsert)) *UpstreamSyncRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamSyncRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetConnectionID sets the "connection_id" field.
func (u *UpstreamSyncRunUpsertOne) SetConnectionID(v int64) *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetConnectionID(v)
	})
}

// UpdateConnectionID sets the "connection_id" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertOne) UpdateConnectionID() *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateConnectionID()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *UpstreamSyncRunUpsertOne) SetFinishedAt(v time.Time) *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertOne) UpdateFinishedAt() *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *UpstreamSyncRunUpsertOne) ClearFinishedAt() *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.ClearFinishedAt()
	})
}

// SetStatus sets the "status" field.
func (u *UpstreamSyncRunUpsertOne) SetStatus(v upstreamsyncrun.Status) *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertOne) UpdateStatus() *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateStatus()
	})
}

// SetKeysFetched sets the "keys_fetched" field.
func (u *UpstreamSyncRunUpsertOne) SetKeysFetched(v int) *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetKeysFetched(v)
	})
}

// AddKeysFetched adds v to the "keys_fetched" field.
func (u *UpstreamSyncRunUpsertOne) AddKeysFetched(v int) *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.AddKeysFetched(v)
	})
}

// UpdateKeysFetched sets the "keys_fetched" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertOne) UpdateKeysFetched() *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateKeysFetched()
	})
}

// SetAccountsMatched sets the "accounts_matched" field.
func (u *UpstreamSyncRunUpsertOne) SetAccountsMatched(v int) *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetAccountsMatched(v)
	})
}

// AddAccountsMatched adds v to the "accounts_matched" field.
func (u *UpstreamSyncRunUpsertOne) AddAccountsMatched(v int) *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.AddAccountsMatched(v)
	})
}

// UpdateAccountsMatched sets the "accounts_matched" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertOne) UpdateAccountsMatched() *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateAccountsMatched()
	})
}

// SetAccountsUpdated sets the "accounts_updated" field.
func (u *UpstreamSyncRunUpsertOne) SetAccountsUpdated(v int) *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetAccountsUpdated(v)
	})
}

// AddAccountsUpdated adds v to the "accounts_updated" field.
func (u *UpstreamSyncRunUpsertOne) AddAccountsUpdated(v int) *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.AddAccountsUpdated(v)
	})
}

// UpdateAccountsUpdated sets the "accounts_updated" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertOne) UpdateAccountsUpdated() *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateAccountsUpdated()
	})
}

// SetAccountsUnchanged sets the "accounts_unchanged" field.
func (u *UpstreamSyncRunUpsertOne) SetAccountsUnchanged(v int) *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetAccountsUnchanged(v)
	})
}

// AddAccountsUnchanged adds v to the "accounts_unchanged" field.
func (u *UpstreamSyncRunUpsertOne) AddAccountsUnchanged(v int) *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.AddAccountsUnchanged(v)
	})
}

// UpdateAccountsUnchanged sets the "accounts_unchanged" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertOne) UpdateAccountsUnchanged() *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateAccountsUnchanged()
	})
}

// SetAccountsUnmatched sets the "accounts_unmatched" field.
func (u *UpstreamSyncRunUpsertOne) SetAccountsUnmatched(v int) *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetAccountsUnmatched(v)
	})
}

// AddAccountsUnmatched adds v to the "accounts_unmatched" field.
func (u *UpstreamSyncRunUpsertOne) AddAccountsUnmatched(v int) *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.AddAccountsUnmatched(v)
	})
}

// UpdateAccountsUnmatched sets the "accounts_unmatched" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertOne) UpdateAccountsUnmatched() *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateAccountsUnmatched()
	})
}

// SetDetails sets the "details" field.
func (u *UpstreamSyncRunUpsertOne) SetDetails(v []upstreamratesync.SyncRunDetail) *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetDetails(v)
	})
}

// UpdateDetails sets the "details" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertOne) UpdateDetails() *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateDetails()
	})
}

// SetError sets the "error" field.
func (u *UpstreamSyncRunUpsertOne) SetError(v string) *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertOne) UpdateError() *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *UpstreamSyncRunUpsertOne) ClearError() *UpstreamSyncRunUpsertOne {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.ClearError()
	})
}

// Exec executes the query.
func (u *UpstreamSyncRunUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamSyncRunCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamSyncRunUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *UpstreamSyncRunUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *UpstreamSyncRunUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// UpstreamSyncRunCreateBulk is the builder for creating many UpstreamSyncRun entities in bulk.
type UpstreamSyncRunCreateBulk struct {
	config
	err      error
	builders []*UpstreamSyncRunCreate
	conflict []sql.ConflictOption
}

// Save creates the UpstreamSyncRun entities in the database.
func (_c *UpstreamSyncRunCreateBulk) Save(ctx context.Context) ([]*UpstreamSyncRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UpstreamSyncRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UpstreamSyncRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UpstreamSyncRunCreateBulk) SaveX(ctx context.Context) []*UpstreamSyncRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UpstreamSyncRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UpstreamSyncRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.UpstreamSyncRun.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.UpstreamSyncRunUpsert) {
//			SetConnectionID(v+v).
//		}).
//		Exec(ctx)
func (_c *UpstreamSyncRunCreateBulk) OnConflict(opts ...sql.ConflictOption) *UpstreamSyncRunUpsertBulk {
	_c.conflict = opts
	return &UpstreamSyncRunUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.UpstreamSyncRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *UpstreamSyncRunCreateBulk) OnConflictColumns(columns ...string) *UpstreamSyncRunUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &UpstreamSyncRunUpsertBulk{
		create: _c,
	}
}

// UpstreamSyncRunUpsertBulk is the builder for "upsert"-ing
// a bulk of UpstreamSyncRun nodes.
type UpstreamSyncRunUpsertBulk struct {
	create *UpstreamSyncRunCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.UpstreamSyncRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *UpstreamSyncRunUpsertBulk) UpdateNewValues() *UpstreamSyncRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.StartedAt(); exists {
				s.SetIgnore(upstreamsyncrun.FieldStartedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.UpstreamSyncRun.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *UpstreamSyncRunUpsertBulk) Ignore() *UpstreamSyncRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *UpstreamSyncRunUpsertBulk) DoNothing() *UpstreamSyncRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the UpstreamSyncRunCreateBulk.OnConflict
// documentation for more info.
func (u *UpstreamSyncRunUpsertBulk) Update(set func(*UpstreamSyncRunUpsert)) *UpstreamSyncRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&UpstreamSyncRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetConnectionID sets the "connection_id" field.
func (u *UpstreamSyncRunUpsertBulk) SetConnectionID(v int64) *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetConnectionID(v)
	})
}

// UpdateConnectionID sets the "connection_id" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertBulk) UpdateConnectionID() *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateConnectionID()
	})
}

// SetFinishedAt sets the "finished_at" field.
func (u *UpstreamSyncRunUpsertBulk) SetFinishedAt(v time.Time) *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetFinishedAt(v)
	})
}

// UpdateFinishedAt sets the "finished_at" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertBulk) UpdateFinishedAt() *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateFinishedAt()
	})
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (u *UpstreamSyncRunUpsertBulk) ClearFinishedAt() *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.ClearFinishedAt()
	})
}

// SetStatus sets the "status" field.
func (u *UpstreamSyncRunUpsertBulk) SetStatus(v upstreamsyncrun.Status) *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertBulk) UpdateStatus() *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateStatus()
	})
}

// SetKeysFetched sets the "keys_fetched" field.
func (u *UpstreamSyncRunUpsertBulk) SetKeysFetched(v int) *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetKeysFetched(v)
	})
}

// AddKeysFetched adds v to the "keys_fetched" field.
func (u *UpstreamSyncRunUpsertBulk) AddKeysFetched(v int) *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.AddKeysFetched(v)
	})
}

// UpdateKeysFetched sets the "keys_fetched" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertBulk) UpdateKeysFetched() *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateKeysFetched()
	})
}

// SetAccountsMatched sets the "accounts_matched" field.
func (u *UpstreamSyncRunUpsertBulk) SetAccountsMatched(v int) *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetAccountsMatched(v)
	})
}

// AddAccountsMatched adds v to the "accounts_matched" field.
func (u *UpstreamSyncRunUpsertBulk) AddAccountsMatched(v int) *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.AddAccountsMatched(v)
	})
}

// UpdateAccountsMatched sets the "accounts_matched" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertBulk) UpdateAccountsMatched() *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateAccountsMatched()
	})
}

// SetAccountsUpdated sets the "accounts_updated" field.
func (u *UpstreamSyncRunUpsertBulk) SetAccountsUpdated(v int) *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetAccountsUpdated(v)
	})
}

// AddAccountsUpdated adds v to the "accounts_updated" field.
func (u *UpstreamSyncRunUpsertBulk) AddAccountsUpdated(v int) *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.AddAccountsUpdated(v)
	})
}

// UpdateAccountsUpdated sets the "accounts_updated" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertBulk) UpdateAccountsUpdated() *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateAccountsUpdated()
	})
}

// SetAccountsUnchanged sets the "accounts_unchanged" field.
func (u *UpstreamSyncRunUpsertBulk) SetAccountsUnchanged(v int) *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetAccountsUnchanged(v)
	})
}

// AddAccountsUnchanged adds v to the "accounts_unchanged" field.
func (u *UpstreamSyncRunUpsertBulk) AddAccountsUnchanged(v int) *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.AddAccountsUnchanged(v)
	})
}

// UpdateAccountsUnchanged sets the "accounts_unchanged" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertBulk) UpdateAccountsUnchanged() *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateAccountsUnchanged()
	})
}

// SetAccountsUnmatched sets the "accounts_unmatched" field.
func (u *UpstreamSyncRunUpsertBulk) SetAccountsUnmatched(v int) *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetAccountsUnmatched(v)
	})
}

// AddAccountsUnmatched adds v to the "accounts_unmatched" field.
func (u *UpstreamSyncRunUpsertBulk) AddAccountsUnmatched(v int) *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.AddAccountsUnmatched(v)
	})
}

// UpdateAccountsUnmatched sets the "accounts_unmatched" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertBulk) UpdateAccountsUnmatched() *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateAccountsUnmatched()
	})
}

// SetDetails sets the "details" field.
func (u *UpstreamSyncRunUpsertBulk) SetDetails(v []upstreamratesync.SyncRunDetail) *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetDetails(v)
	})
}

// UpdateDetails sets the "details" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertBulk) UpdateDetails() *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateDetails()
	})
}

// SetError sets the "error" field.
func (u *UpstreamSyncRunUpsertBulk) SetError(v string) *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.SetError(v)
	})
}

// UpdateError sets the "error" field to the value that was provided on create.
func (u *UpstreamSyncRunUpsertBulk) UpdateError() *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.UpdateError()
	})
}

// ClearError clears the value of the "error" field.
func (u *UpstreamSyncRunUpsertBulk) ClearError() *UpstreamSyncRunUpsertBulk {
	return u.Update(func(s *UpstreamSyncRunUpsert) {
		s.ClearError()
	})
}

// Exec executes the query.
func (u *UpstreamSyncRunUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the UpstreamSyncRunCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for UpstreamSyncRunCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *UpstreamSyncRunUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
