// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconnection"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsyncrun"
	"github.com/Wei-Shaw/sub2api/internal/service/upstreamratesync"
)

// UpstreamSyncRunUpdate is the builder for updating UpstreamSyncRun entities.
type UpstreamSyncRunUpdate struct {
	config
	hooks    []Hook
	mutation *UpstreamSyncRunMutation
}

// Where appends a list predicates to the UpstreamSyncRunUpdate builder.
func (_u *UpstreamSyncRunUpdate) Where(ps ...predicate.UpstreamSyncRun) *UpstreamSyncRunUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetConnectionID sets the "connection_id" field.
func (_u *UpstreamSyncRunUpdate) SetConnectionID(v int64) *UpstreamSyncRunUpdate {
	_u.mutation.SetConnectionID(v)
	return _u
}

// SetNillableConnectionID sets the "connection_id" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdate) SetNillableConnectionID(v *int64) *UpstreamSyncRunUpdate {
	if v != nil {
		_u.SetConnectionID(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *UpstreamSyncRunUpdate) SetFinishedAt(v time.Time) *UpstreamSyncRunUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdate) SetNillableFinishedAt(v *time.Time) *UpstreamSyncRunUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *UpstreamSyncRunUpdate) ClearFinishedAt() *UpstreamSyncRunUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UpstreamSyncRunUpdate) SetStatus(v upstreamsyncrun.Status) *UpstreamSyncRunUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdate) SetNillableStatus(v *upstreamsyncrun.Status) *UpstreamSyncRunUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetKeysFetched sets the "keys_fetched" field.
func (_u *UpstreamSyncRunUpdate) SetKeysFetched(v int) *UpstreamSyncRunUpdate {
	_u.mutation.ResetKeysFetched()
	_u.mutation.SetKeysFetched(v)
	return _u
}

// SetNillableKeysFetched sets the "keys_fetched" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdate) SetNillableKeysFetched(v *int) *UpstreamSyncRunUpdate {
	if v != nil {
		_u.SetKeysFetched(*v)
	}
	return _u
}

// AddKeysFetched adds value to the "keys_fetched" field.
func (_u *UpstreamSyncRunUpdate) AddKeysFetched(v int) *UpstreamSyncRunUpdate {
	_u.mutation.AddKeysFetched(v)
	return _u
}

// SetAccountsMatched sets the "accounts_matched" field.
func (_u *UpstreamSyncRunUpdate) SetAccountsMatched(v int) *UpstreamSyncRunUpdate {
	_u.mutation.ResetAccountsMatched()
	_u.mutation.SetAccountsMatched(v)
	return _u
}

// SetNillableAccountsMatched sets the "accounts_matched" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdate) SetNillableAccountsMatched(v *int) *UpstreamSyncRunUpdate {
	if v != nil {
		_u.SetAccountsMatched(*v)
	}
	return _u
}

// AddAccountsMatched adds value to the "accounts_matched" field.
func (_u *UpstreamSyncRunUpdate) AddAccountsMatched(v int) *UpstreamSyncRunUpdate {
	_u.mutation.AddAccountsMatched(v)
	return _u
}

// SetAccountsUpdated sets the "accounts_updated" field.
func (_u *UpstreamSyncRunUpdate) SetAccountsUpdated(v int) *UpstreamSyncRunUpdate {
	_u.mutation.ResetAccountsUpdated()
	_u.mutation.SetAccountsUpdated(v)
	return _u
}

// SetNillableAccountsUpdated sets the "accounts_updated" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdate) SetNillableAccountsUpdated(v *int) *UpstreamSyncRunUpdate {
	if v != nil {
		_u.SetAccountsUpdated(*v)
	}
	return _u
}

// AddAccountsUpdated adds value to the "accounts_updated" field.
func (_u *UpstreamSyncRunUpdate) AddAccountsUpdated(v int) *UpstreamSyncRunUpdate {
	_u.mutation.AddAccountsUpdated(v)
	return _u
}

// SetAccountsUnchanged sets the "accounts_unchanged" field.
func (_u *UpstreamSyncRunUpdate) SetAccountsUnchanged(v int) *UpstreamSyncRunUpdate {
	_u.mutation.ResetAccountsUnchanged()
	_u.mutation.SetAccountsUnchanged(v)
	return _u
}

// SetNillableAccountsUnchanged sets the "accounts_unchanged" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdate) SetNillableAccountsUnchanged(v *int) *UpstreamSyncRunUpdate {
	if v != nil {
		_u.SetAccountsUnchanged(*v)
	}
	return _u
}

// AddAccountsUnchanged adds value to the "accounts_unchanged" field.
func (_u *UpstreamSyncRunUpdate) AddAccountsUnchanged(v int) *UpstreamSyncRunUpdate {
	_u.mutation.AddAccountsUnchanged(v)
	return _u
}

// SetAccountsUnmatched sets the "accounts_unmatched" field.
func (_u *UpstreamSyncRunUpdate) SetAccountsUnmatched(v int) *UpstreamSyncRunUpdate {
	_u.mutation.ResetAccountsUnmatched()
	_u.mutation.SetAccountsUnmatched(v)
	return _u
}

// SetNillableAccountsUnmatched sets the "accounts_unmatched" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdate) SetNillableAccountsUnmatched(v *int) *UpstreamSyncRunUpdate {
	if v != nil {
		_u.SetAccountsUnmatched(*v)
	}
	return _u
}

// AddAccountsUnmatched adds value to the "accounts_unmatched" field.
func (_u *UpstreamSyncRunUpdate) AddAccountsUnmatched(v int) *UpstreamSyncRunUpdate {
	_u.mutation.AddAccountsUnmatched(v)
	return _u
}

// SetDetails sets the "details" field.
func (_u *UpstreamSyncRunUpdate) SetDetails(v []upstreamratesync.SyncRunDetail) *UpstreamSyncRunUpdate {
	_u.mutation.SetDetails(v)
	return _u
}

// AppendDetails appends value to the "details" field.
func (_u *UpstreamSyncRunUpdate) AppendDetails(v []upstreamratesync.SyncRunDetail) *UpstreamSyncRunUpdate {
	_u.mutation.AppendDetails(v)
	return _u
}

// SetError sets the "error" field.
func (_u *UpstreamSyncRunUpdate) SetError(v string) *UpstreamSyncRunUpdate {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdate) SetNillableError(v *string) *UpstreamSyncRunUpdate {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *UpstreamSyncRunUpdate) ClearError() *UpstreamSyncRunUpdate {
	_u.mutation.ClearError()
	return _u
}

// SetConnection sets the "connection" edge to the UpstreamConnection entity.
func (_u *UpstreamSyncRunUpdate) SetConnection(v *UpstreamConnection) *UpstreamSyncRunUpdate {
	return _u.SetConnectionID(v.ID)
}

// Mutation returns the UpstreamSyncRunMutation object of the builder.
func (_u *UpstreamSyncRunUpdate) Mutation() *UpstreamSyncRunMutation {
	return _u.mutation
}

// ClearConnection clears the "connection" edge to the UpstreamConnection entity.
func (_u *UpstreamSyncRunUpdate) ClearConnection() *UpstreamSyncRunUpdate {
	_u.mutation.ClearConnection()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UpstreamSyncRunUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamSyncRunUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UpstreamSyncRunUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamSyncRunUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamSyncRunUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := upstreamsyncrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeysFetched(); ok {
		if err := upstreamsyncrun.KeysFetchedValidator(v); err != nil {
			return &ValidationError{Name: "keys_fetched", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.keys_fetched": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountsMatched(); ok {
		if err := upstreamsyncrun.AccountsMatchedValidator(v); err != nil {
			return &ValidationError{Name: "accounts_matched", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.accounts_matched": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountsUpdated(); ok {
		if err := upstreamsyncrun.AccountsUpdatedValidator(v); err != nil {
			return &ValidationError{Name: "accounts_updated", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.accounts_updated": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountsUnchanged(); ok {
		if err := upstreamsyncrun.AccountsUnchangedValidator(v); err != nil {
			return &ValidationError{Name: "accounts_unchanged", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.accounts_unchanged": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountsUnmatched(); ok {
		if err := upstreamsyncrun.AccountsUnmatchedValidator(v); err != nil {
			return &ValidationError{Name: "accounts_unmatched", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.accounts_unmatched": %w`, err)}
		}
	}
	if _u.mutation.ConnectionCleared() && len(_u.mutation.ConnectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UpstreamSyncRun.connection"`)
	}
	return nil
}

func (_u *UpstreamSyncRunUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamsyncrun.Table, upstreamsyncrun.Columns, sqlgraph.NewFieldSpec(upstreamsyncrun.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(upstreamsyncrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(upstreamsyncrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(upstreamsyncrun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.KeysFetched(); ok {
		_spec.SetField(upstreamsyncrun.FieldKeysFetched, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKeysFetched(); ok {
		_spec.AddField(upstreamsyncrun.FieldKeysFetched, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccountsMatched(); ok {
		_spec.SetField(upstreamsyncrun.FieldAccountsMatched, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccountsMatched(); ok {
		_spec.AddField(upstreamsyncrun.FieldAccountsMatched, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccountsUpdated(); ok {
		_spec.SetField(upstreamsyncrun.FieldAccountsUpdated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccountsUpdated(); ok {
		_spec.AddField(upstreamsyncrun.FieldAccountsUpdated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccountsUnchanged(); ok {
		_spec.SetField(upstreamsyncrun.FieldAccountsUnchanged, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccountsUnchanged(); ok {
		_spec.AddField(upstreamsyncrun.FieldAccountsUnchanged, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccountsUnmatched(); ok {
		_spec.SetField(upstreamsyncrun.FieldAccountsUnmatched, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccountsUnmatched(); ok {
		_spec.AddField(upstreamsyncrun.FieldAccountsUnmatched, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(upstreamsyncrun.FieldDetails, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDetails(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, upstreamsyncrun.FieldDetails, value)
		})
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(upstreamsyncrun.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(upstreamsyncrun.FieldError, field.TypeString)
	}
	if _u.mutation.ConnectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamsyncrun.ConnectionTable,
			Columns: []string{upstreamsyncrun.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamconnection.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamsyncrun.ConnectionTable,
			Columns: []string{upstreamsyncrun.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamconnection.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamsyncrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UpstreamSyncRunUpdateOne is the builder for updating a single UpstreamSyncRun entity.
type UpstreamSyncRunUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UpstreamSyncRunMutation
}

// SetConnectionID sets the "connection_id" field.
func (_u *UpstreamSyncRunUpdateOne) SetConnectionID(v int64) *UpstreamSyncRunUpdateOne {
	_u.mutation.SetConnectionID(v)
	return _u
}

// SetNillableConnectionID sets the "connection_id" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdateOne) SetNillableConnectionID(v *int64) *UpstreamSyncRunUpdateOne {
	if v != nil {
		_u.SetConnectionID(*v)
	}
	return _u
}

// SetFinishedAt sets the "finished_at" field.
func (_u *UpstreamSyncRunUpdateOne) SetFinishedAt(v time.Time) *UpstreamSyncRunUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finished_at" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdateOne) SetNillableFinishedAt(v *time.Time) *UpstreamSyncRunUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finished_at" field.
func (_u *UpstreamSyncRunUpdateOne) ClearFinishedAt() *UpstreamSyncRunUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetStatus sets the "status" field.
func (_u *UpstreamSyncRunUpdateOne) SetStatus(v upstreamsyncrun.Status) *UpstreamSyncRunUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdateOne) SetNillableStatus(v *upstreamsyncrun.Status) *UpstreamSyncRunUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetKeysFetched sets the "keys_fetched" field.
func (_u *UpstreamSyncRunUpdateOne) SetKeysFetched(v int) *UpstreamSyncRunUpdateOne {
	_u.mutation.ResetKeysFetched()
	_u.mutation.SetKeysFetched(v)
	return _u
}

// SetNillableKeysFetched sets the "keys_fetched" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdateOne) SetNillableKeysFetched(v *int) *UpstreamSyncRunUpdateOne {
	if v != nil {
		_u.SetKeysFetched(*v)
	}
	return _u
}

// AddKeysFetched adds value to the "keys_fetched" field.
func (_u *UpstreamSyncRunUpdateOne) AddKeysFetched(v int) *UpstreamSyncRunUpdateOne {
	_u.mutation.AddKeysFetched(v)
	return _u
}

// SetAccountsMatched sets the "accounts_matched" field.
func (_u *UpstreamSyncRunUpdateOne) SetAccountsMatched(v int) *UpstreamSyncRunUpdateOne {
	_u.mutation.ResetAccountsMatched()
	_u.mutation.SetAccountsMatched(v)
	return _u
}

// SetNillableAccountsMatched sets the "accounts_matched" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdateOne) SetNillableAccountsMatched(v *int) *UpstreamSyncRunUpdateOne {
	if v != nil {
		_u.SetAccountsMatched(*v)
	}
	return _u
}

// AddAccountsMatched adds value to the "accounts_matched" field.
func (_u *UpstreamSyncRunUpdateOne) AddAccountsMatched(v int) *UpstreamSyncRunUpdateOne {
	_u.mutation.AddAccountsMatched(v)
	return _u
}

// SetAccountsUpdated sets the "accounts_updated" field.
func (_u *UpstreamSyncRunUpdateOne) SetAccountsUpdated(v int) *UpstreamSyncRunUpdateOne {
	_u.mutation.ResetAccountsUpdated()
	_u.mutation.SetAccountsUpdated(v)
	return _u
}

// SetNillableAccountsUpdated sets the "accounts_updated" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdateOne) SetNillableAccountsUpdated(v *int) *UpstreamSyncRunUpdateOne {
	if v != nil {
		_u.SetAccountsUpdated(*v)
	}
	return _u
}

// AddAccountsUpdated adds value to the "accounts_updated" field.
func (_u *UpstreamSyncRunUpdateOne) AddAccountsUpdated(v int) *UpstreamSyncRunUpdateOne {
	_u.mutation.AddAccountsUpdated(v)
	return _u
}

// SetAccountsUnchanged sets the "accounts_unchanged" field.
func (_u *UpstreamSyncRunUpdateOne) SetAccountsUnchanged(v int) *UpstreamSyncRunUpdateOne {
	_u.mutation.ResetAccountsUnchanged()
	_u.mutation.SetAccountsUnchanged(v)
	return _u
}

// SetNillableAccountsUnchanged sets the "accounts_unchanged" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdateOne) SetNillableAccountsUnchanged(v *int) *UpstreamSyncRunUpdateOne {
	if v != nil {
		_u.SetAccountsUnchanged(*v)
	}
	return _u
}

// AddAccountsUnchanged adds value to the "accounts_unchanged" field.
func (_u *UpstreamSyncRunUpdateOne) AddAccountsUnchanged(v int) *UpstreamSyncRunUpdateOne {
	_u.mutation.AddAccountsUnchanged(v)
	return _u
}

// SetAccountsUnmatched sets the "accounts_unmatched" field.
func (_u *UpstreamSyncRunUpdateOne) SetAccountsUnmatched(v int) *UpstreamSyncRunUpdateOne {
	_u.mutation.ResetAccountsUnmatched()
	_u.mutation.SetAccountsUnmatched(v)
	return _u
}

// SetNillableAccountsUnmatched sets the "accounts_unmatched" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdateOne) SetNillableAccountsUnmatched(v *int) *UpstreamSyncRunUpdateOne {
	if v != nil {
		_u.SetAccountsUnmatched(*v)
	}
	return _u
}

// AddAccountsUnmatched adds value to the "accounts_unmatched" field.
func (_u *UpstreamSyncRunUpdateOne) AddAccountsUnmatched(v int) *UpstreamSyncRunUpdateOne {
	_u.mutation.AddAccountsUnmatched(v)
	return _u
}

// SetDetails sets the "details" field.
func (_u *UpstreamSyncRunUpdateOne) SetDetails(v []upstreamratesync.SyncRunDetail) *UpstreamSyncRunUpdateOne {
	_u.mutation.SetDetails(v)
	return _u
}

// AppendDetails appends value to the "details" field.
func (_u *UpstreamSyncRunUpdateOne) AppendDetails(v []upstreamratesync.SyncRunDetail) *UpstreamSyncRunUpdateOne {
	_u.mutation.AppendDetails(v)
	return _u
}

// SetError sets the "error" field.
func (_u *UpstreamSyncRunUpdateOne) SetError(v string) *UpstreamSyncRunUpdateOne {
	_u.mutation.SetError(v)
	return _u
}

// SetNillableError sets the "error" field if the given value is not nil.
func (_u *UpstreamSyncRunUpdateOne) SetNillableError(v *string) *UpstreamSyncRunUpdateOne {
	if v != nil {
		_u.SetError(*v)
	}
	return _u
}

// ClearError clears the value of the "error" field.
func (_u *UpstreamSyncRunUpdateOne) ClearError() *UpstreamSyncRunUpdateOne {
	_u.mutation.ClearError()
	return _u
}

// SetConnection sets the "connection" edge to the UpstreamConnection entity.
func (_u *UpstreamSyncRunUpdateOne) SetConnection(v *UpstreamConnection) *UpstreamSyncRunUpdateOne {
	return _u.SetConnectionID(v.ID)
}

// Mutation returns the UpstreamSyncRunMutation object of the builder.
func (_u *UpstreamSyncRunUpdateOne) Mutation() *UpstreamSyncRunMutation {
	return _u.mutation
}

// ClearConnection clears the "connection" edge to the UpstreamConnection entity.
func (_u *UpstreamSyncRunUpdateOne) ClearConnection() *UpstreamSyncRunUpdateOne {
	_u.mutation.ClearConnection()
	return _u
}

// Where appends a list predicates to the UpstreamSyncRunUpdate builder.
func (_u *UpstreamSyncRunUpdateOne) Where(ps ...predicate.UpstreamSyncRun) *UpstreamSyncRunUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UpstreamSyncRunUpdateOne) Select(field string, fields ...string) *UpstreamSyncRunUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UpstreamSyncRun entity.
func (_u *UpstreamSyncRunUpdateOne) Save(ctx context.Context) (*UpstreamSyncRun, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UpstreamSyncRunUpdateOne) SaveX(ctx context.Context) *UpstreamSyncRun {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UpstreamSyncRunUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UpstreamSyncRunUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UpstreamSyncRunUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := upstreamsyncrun.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.KeysFetched(); ok {
		if err := upstreamsyncrun.KeysFetchedValidator(v); err != nil {
			return &ValidationError{Name: "keys_fetched", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.keys_fetched": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountsMatched(); ok {
		if err := upstreamsyncrun.AccountsMatchedValidator(v); err != nil {
			return &ValidationError{Name: "accounts_matched", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.accounts_matched": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountsUpdated(); ok {
		if err := upstreamsyncrun.AccountsUpdatedValidator(v); err != nil {
			return &ValidationError{Name: "accounts_updated", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.accounts_updated": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountsUnchanged(); ok {
		if err := upstreamsyncrun.AccountsUnchangedValidator(v); err != nil {
			return &ValidationError{Name: "accounts_unchanged", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.accounts_unchanged": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AccountsUnmatched(); ok {
		if err := upstreamsyncrun.AccountsUnmatchedValidator(v); err != nil {
			return &ValidationError{Name: "accounts_unmatched", err: fmt.Errorf(`ent: validator failed for field "UpstreamSyncRun.accounts_unmatched": %w`, err)}
		}
	}
	if _u.mutation.ConnectionCleared() && len(_u.mutation.ConnectionIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UpstreamSyncRun.connection"`)
	}
	return nil
}

func (_u *UpstreamSyncRunUpdateOne) sqlSave(ctx context.Context) (_node *UpstreamSyncRun, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(upstreamsyncrun.Table, upstreamsyncrun.Columns, sqlgraph.NewFieldSpec(upstreamsyncrun.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "UpstreamSyncRun.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, upstreamsyncrun.FieldID)
		for _, f := range fields {
			if !upstreamsyncrun.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != upstreamsyncrun.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(upstreamsyncrun.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(upstreamsyncrun.FieldFinishedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(upstreamsyncrun.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.KeysFetched(); ok {
		_spec.SetField(upstreamsyncrun.FieldKeysFetched, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedKeysFetched(); ok {
		_spec.AddField(upstreamsyncrun.FieldKeysFetched, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccountsMatched(); ok {
		_spec.SetField(upstreamsyncrun.FieldAccountsMatched, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccountsMatched(); ok {
		_spec.AddField(upstreamsyncrun.FieldAccountsMatched, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccountsUpdated(); ok {
		_spec.SetField(upstreamsyncrun.FieldAccountsUpdated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccountsUpdated(); ok {
		_spec.AddField(upstreamsyncrun.FieldAccountsUpdated, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccountsUnchanged(); ok {
		_spec.SetField(upstreamsyncrun.FieldAccountsUnchanged, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccountsUnchanged(); ok {
		_spec.AddField(upstreamsyncrun.FieldAccountsUnchanged, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AccountsUnmatched(); ok {
		_spec.SetField(upstreamsyncrun.FieldAccountsUnmatched, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAccountsUnmatched(); ok {
		_spec.AddField(upstreamsyncrun.FieldAccountsUnmatched, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(upstreamsyncrun.FieldDetails, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDetails(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, upstreamsyncrun.FieldDetails, value)
		})
	}
	if value, ok := _u.mutation.Error(); ok {
		_spec.SetField(upstreamsyncrun.FieldError, field.TypeString, value)
	}
	if _u.mutation.ErrorCleared() {
		_spec.ClearField(upstreamsyncrun.FieldError, field.TypeString)
	}
	if _u.mutation.ConnectionCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamsyncrun.ConnectionTable,
			Columns: []string{upstreamsyncrun.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamconnection.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ConnectionIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   upstreamsyncrun.ConnectionTable,
			Columns: []string{upstreamsyncrun.ConnectionColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(upstreamconnection.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UpstreamSyncRun{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{upstreamsyncrun.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
