// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/upstreamconnection"
	"github.com/Wei-Shaw/sub2api/ent/upstreamsyncrun"
	"github.com/Wei-Shaw/sub2api/internal/service/upstreamratesync"
)

// UpstreamSyncRun is the model entity for the UpstreamSyncRun schema.
type UpstreamSyncRun struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// ConnectionID holds the value of the "connection_id" field.
	ConnectionID int64 `json:"connection_id,omitempty"`
	// StartedAt holds the value of the "started_at" field.
	StartedAt time.Time `json:"started_at,omitempty"`
	// NULL 表示进行中
	FinishedAt *time.Time `json:"finished_at,omitempty"`
	// Status holds the value of the "status" field.
	Status upstreamsyncrun.Status `json:"status,omitempty"`
	// 上游拉到的 key 总数
	KeysFetched int `json:"keys_fetched,omitempty"`
	// 匹配到本地账号数
	AccountsMatched int `json:"accounts_matched,omitempty"`
	// 实际写回数
	AccountsUpdated int `json:"accounts_updated,omitempty"`
	// 值未变化跳过数
	AccountsUnchanged int `json:"accounts_unchanged,omitempty"`
	// 本地 key 在上游找不到数
	AccountsUnmatched int `json:"accounts_unmatched,omitempty"`
	// 明细数组 {account_id,key_prefix,group_name,old_rate,new_rate,action}
	Details []upstreamratesync.SyncRunDetail `json:"details,omitempty"`
	// 失败原因摘要（脱敏）
	Error string `json:"error,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UpstreamSyncRunQuery when eager-loading is set.
	Edges        UpstreamSyncRunEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UpstreamSyncRunEdges holds the relations/edges for other nodes in the graph.
type UpstreamSyncRunEdges struct {
	// Connection holds the value of the connection edge.
	Connection *UpstreamConnection `json:"connection,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ConnectionOrErr returns the Connection value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UpstreamSyncRunEdges) ConnectionOrErr() (*UpstreamConnection, error) {
	if e.Connection != nil {
		return e.Connection, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: upstreamconnection.Label}
	}
	return nil, &NotLoadedError{edge: "connection"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*UpstreamSyncRun) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case upstreamsyncrun.FieldDetails:
			values[i] = new([]byte)
		case upstreamsyncrun.FieldID, upstreamsyncrun.FieldConnectionID, upstreamsyncrun.FieldKeysFetched, upstreamsyncrun.FieldAccountsMatched, upstreamsyncrun.FieldAccountsUpdated, upstreamsyncrun.FieldAccountsUnchanged, upstreamsyncrun.FieldAccountsUnmatched:
			values[i] = new(sql.NullInt64)
		case upstreamsyncrun.FieldStatus, upstreamsyncrun.FieldError:
			values[i] = new(sql.NullString)
		case upstreamsyncrun.FieldStartedAt, upstreamsyncrun.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the UpstreamSyncRun fields.
func (_m *UpstreamSyncRun) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case upstreamsyncrun.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case upstreamsyncrun.FieldConnectionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field connection_id", values[i])
			} else if value.Valid {
				_m.ConnectionID = value.Int64
			}
		case upstreamsyncrun.FieldStartedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field started_at", values[i])
			} else if value.Valid {
				_m.StartedAt = value.Time
			}
		case upstreamsyncrun.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finished_at", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case upstreamsyncrun.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = upstreamsyncrun.Status(value.String)
			}
		case upstreamsyncrun.FieldKeysFetched:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field keys_fetched", values[i])
			} else if value.Valid {
				_m.KeysFetched = int(value.Int64)
			}
		case upstreamsyncrun.FieldAccountsMatched:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field accounts_matched", values[i])
			} else if value.Valid {
				_m.AccountsMatched = int(value.Int64)
			}
		case upstreamsyncrun.FieldAccountsUpdated:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field accounts_updated", values[i])
			} else if value.Valid {
				_m.AccountsUpdated = int(value.Int64)
			}
		case upstreamsyncrun.FieldAccountsUnchanged:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field accounts_unchanged", values[i])
			} else if value.Valid {
				_m.AccountsUnchanged = int(value.Int64)
			}
		case upstreamsyncrun.FieldAccountsUnmatched:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field accounts_unmatched", values[i])
			} else if value.Valid {
				_m.AccountsUnmatched = int(value.Int64)
			}
		case upstreamsyncrun.FieldDetails:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field details", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Details); err != nil {
					return fmt.Errorf("unmarshal field details: %w", err)
				}
			}
		case upstreamsyncrun.FieldError:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error", values[i])
			} else if value.Valid {
				_m.Error = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the UpstreamSyncRun.
// This includes values selected through modifiers, order, etc.
func (_m *UpstreamSyncRun) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryConnection queries the "connection" edge of the UpstreamSyncRun entity.
func (_m *UpstreamSyncRun) QueryConnection() *UpstreamConnectionQuery {
	return NewUpstreamSyncRunClient(_m.config).QueryConnection(_m)
}

// Update returns a builder for updating this UpstreamSyncRun.
// Note that you need to call UpstreamSyncRun.Unwrap() before calling this method if this UpstreamSyncRun
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *UpstreamSyncRun) Update() *UpstreamSyncRunUpdateOne {
	return NewUpstreamSyncRunClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the UpstreamSyncRun entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *UpstreamSyncRun) Unwrap() *UpstreamSyncRun {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: UpstreamSyncRun is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *UpstreamSyncRun) String() string {
	var builder strings.Builder
	builder.WriteString("UpstreamSyncRun(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("connection_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConnectionID))
	builder.WriteString(", ")
	builder.WriteString("started_at=")
	builder.WriteString(_m.StartedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finished_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	builder.WriteString("keys_fetched=")
	builder.WriteString(fmt.Sprintf("%v", _m.KeysFetched))
	builder.WriteString(", ")
	builder.WriteString("accounts_matched=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountsMatched))
	builder.WriteString(", ")
	builder.WriteString("accounts_updated=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountsUpdated))
	builder.WriteString(", ")
	builder.WriteString("accounts_unchanged=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountsUnchanged))
	builder.WriteString(", ")
	builder.WriteString("accounts_unmatched=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountsUnmatched))
	builder.WriteString(", ")
	builder.WriteString("details=")
	builder.WriteString(fmt.Sprintf("%v", _m.Details))
	builder.WriteString(", ")
	builder.WriteString("error=")
	builder.WriteString(_m.Error)
	builder.WriteByte(')')
	return builder.String()
}

// UpstreamSyncRuns is a parsable slice of UpstreamSyncRun.
type UpstreamSyncRuns []*UpstreamSyncRun
