// Code generated by ent, DO NOT EDIT.

package upstreamsyncrun

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/internal/service/upstreamratesync"
)

const (
	// Label holds the string label denoting the upstreamsyncrun type in the database.
	Label = "upstream_sync_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldConnectionID holds the string denoting the connection_id field in the database.
	FieldConnectionID = "connection_id"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldFinishedAt holds the string denoting the finished_at field in the database.
	FieldFinishedAt = "finished_at"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldKeysFetched holds the string denoting the keys_fetched field in the database.
	FieldKeysFetched = "keys_fetched"
	// FieldAccountsMatched holds the string denoting the accounts_matched field in the database.
	FieldAccountsMatched = "accounts_matched"
	// FieldAccountsUpdated holds the string denoting the accounts_updated field in the database.
	FieldAccountsUpdated = "accounts_updated"
	// FieldAccountsUnchanged holds the string denoting the accounts_unchanged field in the database.
	FieldAccountsUnchanged = "accounts_unchanged"
	// FieldAccountsUnmatched holds the string denoting the accounts_unmatched field in the database.
	FieldAccountsUnmatched = "accounts_unmatched"
	// FieldDetails holds the string denoting the details field in the database.
	FieldDetails = "details"
	// FieldError holds the string denoting the error field in the database.
	FieldError = "error"
	// EdgeConnection holds the string denoting the connection edge name in mutations.
	EdgeConnection = "connection"
	// Table holds the table name of the upstreamsyncrun in the database.
	Table = "upstream_sync_runs"
	// ConnectionTable is the table that holds the connection relation/edge.
	ConnectionTable = "upstream_sync_runs"
	// ConnectionInverseTable is the table name for the UpstreamConnection entity.
	// It exists in this package in order to avoid circular dependency with the "upstreamconnection" package.
	ConnectionInverseTable = "upstream_connections"
	// ConnectionColumn is the table column denoting the connection relation/edge.
	ConnectionColumn = "connection_id"
)

// Columns holds all SQL columns for upstreamsyncrun fields.
var Columns = []string{
	FieldID,
	FieldConnectionID,
	FieldStartedAt,
	FieldFinishedAt,
	FieldStatus,
	FieldKeysFetched,
	FieldAccountsMatched,
	FieldAccountsUpdated,
	FieldAccountsUnchanged,
	FieldAccountsUnmatched,
	FieldDetails,
	FieldError,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStartedAt holds the default value on creation for the "started_at" field.
	DefaultStartedAt func() time.Time
	// DefaultKeysFetched holds the default value on creation for the "keys_fetched" field.
	DefaultKeysFetched int
	// KeysFetchedValidator is a validator for the "keys_fetched" field. It is called by the builders before save.
	KeysFetchedValidator func(int) error
	// DefaultAccountsMatched holds the default value on creation for the "accounts_matched" field.
	DefaultAccountsMatched int
	// AccountsMatchedValidator is a validator for the "accounts_matched" field. It is called by the builders before save.
	AccountsMatchedValidator func(int) error
	// DefaultAccountsUpdated holds the default value on creation for the "accounts_updated" field.
	DefaultAccountsUpdated int
	// AccountsUpdatedValidator is a validator for the "accounts_updated" field. It is called by the builders before save.
	AccountsUpdatedValidator func(int) error
	// DefaultAccountsUnchanged holds the default value on creation for the "accounts_unchanged" field.
	DefaultAccountsUnchanged int
	// AccountsUnchangedValidator is a validator for the "accounts_unchanged" field. It is called by the builders before save.
	AccountsUnchangedValidator func(int) error
	// DefaultAccountsUnmatched holds the default value on creation for the "accounts_unmatched" field.
	DefaultAccountsUnmatched int
	// AccountsUnmatchedValidator is a validator for the "accounts_unmatched" field. It is called by the builders before save.
	AccountsUnmatchedValidator func(int) error
	// DefaultDetails holds the default value on creation for the "details" field.
	DefaultDetails []upstreamratesync.SyncRunDetail
)

// Status defines the type for the "status" enum field.
type Status string

// StatusSuccess is the default value of the Status enum.
const DefaultStatus = StatusSuccess

// Status values.
const (
	StatusSuccess Status = "success"
	StatusPartial Status = "partial"
	StatusFailed  Status = "failed"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusSuccess, StatusPartial, StatusFailed:
		return nil
	default:
		return fmt.Errorf("upstreamsyncrun: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the UpstreamSyncRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByConnectionID orders the results by the connection_id field.
func ByConnectionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConnectionID, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finished_at field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByKeysFetched orders the results by the keys_fetched field.
func ByKeysFetched(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKeysFetched, opts...).ToFunc()
}

// ByAccountsMatched orders the results by the accounts_matched field.
func ByAccountsMatched(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountsMatched, opts...).ToFunc()
}

// ByAccountsUpdated orders the results by the accounts_updated field.
func ByAccountsUpdated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountsUpdated, opts...).ToFunc()
}

// ByAccountsUnchanged orders the results by the accounts_unchanged field.
func ByAccountsUnchanged(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountsUnchanged, opts...).ToFunc()
}

// ByAccountsUnmatched orders the results by the accounts_unmatched field.
func ByAccountsUnmatched(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountsUnmatched, opts...).ToFunc()
}

// ByError orders the results by the error field.
func ByError(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldError, opts...).ToFunc()
}

// ByConnectionField orders the results by connection field.
func ByConnectionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newConnectionStep(), sql.OrderByField(field, opts...))
	}
}
func newConnectionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ConnectionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ConnectionTable, ConnectionColumn),
	)
}
