// Code generated by ent, DO NOT EDIT.

package upstreamsyncrun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLTE(FieldID, id))
}

// ConnectionID applies equality check predicate on the "connection_id" field. It's identical to ConnectionIDEQ.
func ConnectionID(v int64) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldConnectionID, v))
}

// StartedAt applies equality check predicate on the "started_at" field. It's identical to StartedAtEQ.
func StartedAt(v time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldStartedAt, v))
}

// FinishedAt applies equality check predicate on the "finished_at" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldFinishedAt, v))
}

// KeysFetched applies equality check predicate on the "keys_fetched" field. It's identical to KeysFetchedEQ.
func KeysFetched(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldKeysFetched, v))
}

// AccountsMatched applies equality check predicate on the "accounts_matched" field. It's identical to AccountsMatchedEQ.
func AccountsMatched(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldAccountsMatched, v))
}

// AccountsUpdated applies equality check predicate on the "accounts_updated" field. It's identical to AccountsUpdatedEQ.
func AccountsUpdated(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldAccountsUpdated, v))
}

// AccountsUnchanged applies equality check predicate on the "accounts_unchanged" field. It's identical to AccountsUnchangedEQ.
func AccountsUnchanged(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldAccountsUnchanged, v))
}

// AccountsUnmatched applies equality check predicate on the "accounts_unmatched" field. It's identical to AccountsUnmatchedEQ.
func AccountsUnmatched(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldAccountsUnmatched, v))
}

// Error applies equality check predicate on the "error" field. It's identical to ErrorEQ.
func Error(v string) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldError, v))
}

// ConnectionIDEQ applies the EQ predicate on the "connection_id" field.
func ConnectionIDEQ(v int64) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldConnectionID, v))
}

// ConnectionIDNEQ applies the NEQ predicate on the "connection_id" field.
func ConnectionIDNEQ(v int64) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNEQ(FieldConnectionID, v))
}

// ConnectionIDIn applies the In predicate on the "connection_id" field.
func ConnectionIDIn(vs ...int64) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldIn(FieldConnectionID, vs...))
}

// ConnectionIDNotIn applies the NotIn predicate on the "connection_id" field.
func ConnectionIDNotIn(vs ...int64) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNotIn(FieldConnectionID, vs...))
}

// StartedAtEQ applies the EQ predicate on the "started_at" field.
func StartedAtEQ(v time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldStartedAt, v))
}

// StartedAtNEQ applies the NEQ predicate on the "started_at" field.
func StartedAtNEQ(v time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNEQ(FieldStartedAt, v))
}

// StartedAtIn applies the In predicate on the "started_at" field.
func StartedAtIn(vs ...time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldIn(FieldStartedAt, vs...))
}

// StartedAtNotIn applies the NotIn predicate on the "started_at" field.
func StartedAtNotIn(vs ...time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNotIn(FieldStartedAt, vs...))
}

// StartedAtGT applies the GT predicate on the "started_at" field.
func StartedAtGT(v time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGT(FieldStartedAt, v))
}

// StartedAtGTE applies the GTE predicate on the "started_at" field.
func StartedAtGTE(v time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGTE(FieldStartedAt, v))
}

// StartedAtLT applies the LT predicate on the "started_at" field.
func StartedAtLT(v time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLT(FieldStartedAt, v))
}

// StartedAtLTE applies the LTE predicate on the "started_at" field.
func StartedAtLTE(v time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLTE(FieldStartedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finished_at" field.
func FinishedAtEQ(v time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finished_at" field.
func FinishedAtNEQ(v time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finished_at" field.
func FinishedAtIn(vs ...time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finished_at" field.
func FinishedAtNotIn(vs ...time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finished_at" field.
func FinishedAtGT(v time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finished_at" field.
func FinishedAtGTE(v time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finished_at" field.
func FinishedAtLT(v time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finished_at" field.
func FinishedAtLTE(v time.Time) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finished_at" field.
func FinishedAtIsNil() predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finished_at" field.
func FinishedAtNotNil() predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNotNull(FieldFinishedAt))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNotIn(FieldStatus, vs...))
}

// KeysFetchedEQ applies the EQ predicate on the "keys_fetched" field.
func KeysFetchedEQ(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldKeysFetched, v))
}

// KeysFetchedNEQ applies the NEQ predicate on the "keys_fetched" field.
func KeysFetchedNEQ(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNEQ(FieldKeysFetched, v))
}

// KeysFetchedIn applies the In predicate on the "keys_fetched" field.
func KeysFetchedIn(vs ...int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldIn(FieldKeysFetched, vs...))
}

// KeysFetchedNotIn applies the NotIn predicate on the "keys_fetched" field.
func KeysFetchedNotIn(vs ...int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNotIn(FieldKeysFetched, vs...))
}

// KeysFetchedGT applies the GT predicate on the "keys_fetched" field.
func KeysFetchedGT(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGT(FieldKeysFetched, v))
}

// KeysFetchedGTE applies the GTE predicate on the "keys_fetched" field.
func KeysFetchedGTE(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGTE(FieldKeysFetched, v))
}

// KeysFetchedLT applies the LT predicate on the "keys_fetched" field.
func KeysFetchedLT(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLT(FieldKeysFetched, v))
}

// KeysFetchedLTE applies the LTE predicate on the "keys_fetched" field.
func KeysFetchedLTE(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLTE(FieldKeysFetched, v))
}

// AccountsMatchedEQ applies the EQ predicate on the "accounts_matched" field.
func AccountsMatchedEQ(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldAccountsMatched, v))
}

// AccountsMatchedNEQ applies the NEQ predicate on the "accounts_matched" field.
func AccountsMatchedNEQ(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNEQ(FieldAccountsMatched, v))
}

// AccountsMatchedIn applies the In predicate on the "accounts_matched" field.
func AccountsMatchedIn(vs ...int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldIn(FieldAccountsMatched, vs...))
}

// AccountsMatchedNotIn applies the NotIn predicate on the "accounts_matched" field.
func AccountsMatchedNotIn(vs ...int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNotIn(FieldAccountsMatched, vs...))
}

// AccountsMatchedGT applies the GT predicate on the "accounts_matched" field.
func AccountsMatchedGT(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGT(FieldAccountsMatched, v))
}

// AccountsMatchedGTE applies the GTE predicate on the "accounts_matched" field.
func AccountsMatchedGTE(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGTE(FieldAccountsMatched, v))
}

// AccountsMatchedLT applies the LT predicate on the "accounts_matched" field.
func AccountsMatchedLT(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLT(FieldAccountsMatched, v))
}

// AccountsMatchedLTE applies the LTE predicate on the "accounts_matched" field.
func AccountsMatchedLTE(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLTE(FieldAccountsMatched, v))
}

// AccountsUpdatedEQ applies the EQ predicate on the "accounts_updated" field.
func AccountsUpdatedEQ(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldAccountsUpdated, v))
}

// AccountsUpdatedNEQ applies the NEQ predicate on the "accounts_updated" field.
func AccountsUpdatedNEQ(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNEQ(FieldAccountsUpdated, v))
}

// AccountsUpdatedIn applies the In predicate on the "accounts_updated" field.
func AccountsUpdatedIn(vs ...int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldIn(FieldAccountsUpdated, vs...))
}

// AccountsUpdatedNotIn applies the NotIn predicate on the "accounts_updated" field.
func AccountsUpdatedNotIn(vs ...int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNotIn(FieldAccountsUpdated, vs...))
}

// AccountsUpdatedGT applies the GT predicate on the "accounts_updated" field.
func AccountsUpdatedGT(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGT(FieldAccountsUpdated, v))
}

// AccountsUpdatedGTE applies the GTE predicate on the "accounts_updated" field.
func AccountsUpdatedGTE(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGTE(FieldAccountsUpdated, v))
}

// AccountsUpdatedLT applies the LT predicate on the "accounts_updated" field.
func AccountsUpdatedLT(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLT(FieldAccountsUpdated, v))
}

// AccountsUpdatedLTE applies the LTE predicate on the "accounts_updated" field.
func AccountsUpdatedLTE(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLTE(FieldAccountsUpdated, v))
}

// AccountsUnchangedEQ applies the EQ predicate on the "accounts_unchanged" field.
func AccountsUnchangedEQ(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldAccountsUnchanged, v))
}

// AccountsUnchangedNEQ applies the NEQ predicate on the "accounts_unchanged" field.
func AccountsUnchangedNEQ(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNEQ(FieldAccountsUnchanged, v))
}

// AccountsUnchangedIn applies the In predicate on the "accounts_unchanged" field.
func AccountsUnchangedIn(vs ...int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldIn(FieldAccountsUnchanged, vs...))
}

// AccountsUnchangedNotIn applies the NotIn predicate on the "accounts_unchanged" field.
func AccountsUnchangedNotIn(vs ...int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNotIn(FieldAccountsUnchanged, vs...))
}

// AccountsUnchangedGT applies the GT predicate on the "accounts_unchanged" field.
func AccountsUnchangedGT(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGT(FieldAccountsUnchanged, v))
}

// AccountsUnchangedGTE applies the GTE predicate on the "accounts_unchanged" field.
func AccountsUnchangedGTE(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGTE(FieldAccountsUnchanged, v))
}

// AccountsUnchangedLT applies the LT predicate on the "accounts_unchanged" field.
func AccountsUnchangedLT(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLT(FieldAccountsUnchanged, v))
}

// AccountsUnchangedLTE applies the LTE predicate on the "accounts_unchanged" field.
func AccountsUnchangedLTE(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLTE(FieldAccountsUnchanged, v))
}

// AccountsUnmatchedEQ applies the EQ predicate on the "accounts_unmatched" field.
func AccountsUnmatchedEQ(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldAccountsUnmatched, v))
}

// AccountsUnmatchedNEQ applies the NEQ predicate on the "accounts_unmatched" field.
func AccountsUnmatchedNEQ(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNEQ(FieldAccountsUnmatched, v))
}

// AccountsUnmatchedIn applies the In predicate on the "accounts_unmatched" field.
func AccountsUnmatchedIn(vs ...int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldIn(FieldAccountsUnmatched, vs...))
}

// AccountsUnmatchedNotIn applies the NotIn predicate on the "accounts_unmatched" field.
func AccountsUnmatchedNotIn(vs ...int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNotIn(FieldAccountsUnmatched, vs...))
}

// AccountsUnmatchedGT applies the GT predicate on the "accounts_unmatched" field.
func AccountsUnmatchedGT(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGT(FieldAccountsUnmatched, v))
}

// AccountsUnmatchedGTE applies the GTE predicate on the "accounts_unmatched" field.
func AccountsUnmatchedGTE(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGTE(FieldAccountsUnmatched, v))
}

// AccountsUnmatchedLT applies the LT predicate on the "accounts_unmatched" field.
func AccountsUnmatchedLT(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLT(FieldAccountsUnmatched, v))
}

// AccountsUnmatchedLTE applies the LTE predicate on the "accounts_unmatched" field.
func AccountsUnmatchedLTE(v int) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLTE(FieldAccountsUnmatched, v))
}

// ErrorEQ applies the EQ predicate on the "error" field.
func ErrorEQ(v string) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEQ(FieldError, v))
}

// ErrorNEQ applies the NEQ predicate on the "error" field.
func ErrorNEQ(v string) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNEQ(FieldError, v))
}

// ErrorIn applies the In predicate on the "error" field.
func ErrorIn(vs ...string) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldIn(FieldError, vs...))
}

// ErrorNotIn applies the NotIn predicate on the "error" field.
func ErrorNotIn(vs ...string) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNotIn(FieldError, vs...))
}

// ErrorGT applies the GT predicate on the "error" field.
func ErrorGT(v string) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGT(FieldError, v))
}

// ErrorGTE applies the GTE predicate on the "error" field.
func ErrorGTE(v string) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldGTE(FieldError, v))
}

// ErrorLT applies the LT predicate on the "error" field.
func ErrorLT(v string) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLT(FieldError, v))
}

// ErrorLTE applies the LTE predicate on the "error" field.
func ErrorLTE(v string) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldLTE(FieldError, v))
}

// ErrorContains applies the Contains predicate on the "error" field.
func ErrorContains(v string) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldContains(FieldError, v))
}

// ErrorHasPrefix applies the HasPrefix predicate on the "error" field.
func ErrorHasPrefix(v string) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldHasPrefix(FieldError, v))
}

// ErrorHasSuffix applies the HasSuffix predicate on the "error" field.
func ErrorHasSuffix(v string) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldHasSuffix(FieldError, v))
}

// ErrorIsNil applies the IsNil predicate on the "error" field.
func ErrorIsNil() predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldIsNull(FieldError))
}

// ErrorNotNil applies the NotNil predicate on the "error" field.
func ErrorNotNil() predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldNotNull(FieldError))
}

// ErrorEqualFold applies the EqualFold predicate on the "error" field.
func ErrorEqualFold(v string) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldEqualFold(FieldError, v))
}

// ErrorContainsFold applies the ContainsFold predicate on the "error" field.
func ErrorContainsFold(v string) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.FieldContainsFold(FieldError, v))
}

// HasConnection applies the HasEdge predicate on the "connection" edge.
func HasConnection() predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ConnectionTable, ConnectionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasConnectionWith applies the HasEdge predicate on the "connection" edge with a given conditions (other predicates).
func HasConnectionWith(preds ...predicate.UpstreamConnection) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(func(s *sql.Selector) {
		step := newConnectionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UpstreamSyncRun) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UpstreamSyncRun) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UpstreamSyncRun) predicate.UpstreamSyncRun {
	return predicate.UpstreamSyncRun(sql.NotPredicates(p))
}
